### ISSUE TITLE
multiball_locks not valid in machine config, contrary to docs

### ISSUE THREAD

**Issue by Wolfmarsh** [missionpinball/mpf#1001]
When trying to define multiball_locks in the machine config, you get the following error: "Found a "multiball_locks:" section in config file C:\spaceballs\config\multiballs.yaml, but that section is not valid in machine config files."

According to the docs at http://docs.missionpinball.org/en/latest/config/multiball_locks.html it is valid in machine configs. 

Wasn't sure which was correct, so I just filed an issue.

**Comment by toomanybrians** [comment]
This is definitely a docs issue. multiball_locks is only valid in mode configs. I'll create an issue in mpf-docs. Thanks!
