### ISSUE TITLE
Review player_add_success usage

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1013]
We use player_add_success in bcp_interface and extra_ball_group but it no longer exists in game/player in 0.50/dev.

**Comment by qcapen** [comment]
'player_add_success' event was removed and replaced with 'player_added' in 0.50 to be consistent with other event naming conventions.  We definitely need to update existing occurrences of 'player_add_success'.

**Comment by qcapen** [comment]
In addition, 'player_will_add' and 'player_adding' (queue event) have been added to 0.50.
