### ISSUE TITLE
Add settings for tilt in service

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1031]
Number of tilt warnings and debouce time should be configurable  in service menu

**Comment by hfarooqui98** [comment]
Hi, I am looking to help contribute and solve this issue but this will be my first time working on an opensource project so I would really appreciate it if you could point me in the right direction to start working on this issue

**Comment by jabdoa2** [comment]
Hi Hummad,

that is awesome! As first step install MPF (http://docs.missionpinball.org/en/latest/about/contributing_to_mpf.html) and play with one of our example machines (https://github.com/missionpinball/mpf-examples/tree/dev/demo_man). Try if the unit tests work for you.

This change is similar to a change in the credits mode: https://github.com/missionpinball/mpf/commit/11335f308302d7d735d4f8f777189d2e4b974578. You need to change the type of `warnings_to_tilt`, `multiple_hit_window` and `settle_time` into a placeholder in config_spec (https://github.com/missionpinball/mpf/blob/dev/mpf/core/config_spec.py#L1250). Then evaluate them before use in the mode (as credits mode). Tilt mode is tested so if the unit tests pass you likely did it right.

**Comment by thakkardharmik** [comment]
@jabdoa2 Shall I take this up? I am a newbie.

**Comment by jabdoa2** [comment]
Your choice. Both issues are open. Let me know if you have any questions.
