### ISSUE TITLE
Update logic OR docs for achievement events

### ISSUE THREAD

**Issue by avanwinkle** [missionpinball/mpf#1050]
There is an inconsistency between the behavior and the documentation for achievements that should be reconciled to avoid frustrating developers 😛 

I'm happy to tackle this work, just looking for feedback as to which of these is the "desired" behavior.

### Docs
According to the documentation, `events_when_<state>` is additive to the default event:

> **Events posted by achievements**
Note that all achievements will always post events in the form achievement_(name)\_state\_(state) when they change state. The events listed below are in additional to that event.

http://docs.missionpinball.org/en/dev/config/achievements.html

### Behavior
However in the code, the behavior is explicitly a default-or-replace:
```
for state in states:
    if not config['events_when_{}'.format(state)]:
        config['events_when_{}'.format(state)] = [
            "achievement_{}_state_{}".format(self.name, state)]
```
https://github.com/missionpinball/mpf/blob/dev/mpf/devices/achievement.py#L58

**Comment by jabdoa2** [comment]
Good find. I guess it would be fine to just fix the documentation. What do you think?

**Comment by avanwinkle** [comment]
Cool, made a PR for updating the docs.
