### ISSUE TITLE
Possible bug in 'light.py'

### ISSUE THREAD

**Issue by avanwinkle** [missionpinball/mpf#1054]
While building out some new lighting shows I encountered a recurring crash due to an unexpected Type, and traced it down to a possible typo in `mpf/devices/light.py`.

In the method `_get_color_and_fade`, which is designated as returning `Tuple[RGBColor, int]`, there are five `return` statements. Four of them return a color and a number:
```
451: return RGBColor('off'), -1
455: return color_settings['dest_color'], -1
461: return color_settings['dest_color'], -1
475: return RGBColor.blend(color_settings['start_color'], color_settings['dest_color'], ratio), max_fade_ms
```
Line 461, however, returns two numbers:
```return color_settings['dest_time'], int((color_settings['dest_time'] - current_time) / 1000)```

I believe it's just a typo and `dest_time` is meant to be `dest_color`, as it is in the other return statements:
```return color_settings['dest_color'], int((color_settings['dest_time'] - current_time) / 1000)```

https://github.com/missionpinball/mpf/blame/dev/mpf/devices/light.py#L466

If folks agree, I'm happy to branch and make a PR for the quick fix.

**Comment by jabdoa2** [comment]
That makes sense. Thanks for finding! I wounder why the tests did not catch it.
