### ISSUE TITLE
mpf both crashes with termios.error: (19, 'Operation not supported by device')

### ISSUE THREAD

**Issue by muffler-aus** [missionpinball/mpf#1075]
When running mpf both I get an error: termios.error: (19, 'Operation not supported by device') If I run MPF and MC in seperate terminals it appears to work fine. After some discussion with fellow MPF users/contributors I was pointed at commands/both.py. 

Looking through this I found that I can reproduce the error with this minimal code:

```
import sys
import termios
import multiprocessing
from time import sleep


def _start():
     tbs = termios.tcgetattr(sys.stdin)
     sleep(10)     

mpf = multiprocessing.Process(target=_start)
mpf.start()
mpf.join()

When termios calls tcgetattr on sys.stdin inside the multiprocess it errors out.

I will submit a PR that works around this issue but I need to have it tested on other platforms (Linux/Windows).

**Comment by jabdoa2** [comment]
fixed by #1076
