### ISSUE TITLE
Unexpected behavior with ball_device, multiball_lock, and multiball

### ISSUE THREAD

**Issue by avanwinkle** [missionpinball/mpf#1083]
There is a bug in MPF multiball-locking logic that results in undesirable behavior when using ball_devices that physically lock multiple balls. The bug stems from how locked balls are claimed, counted, and replaced on the playfield in the method `MultiballLock._lock_ball`. 

When a multiball_lock physically locks a ball, the `balls_in_play` count is not decreased (which could trigger a game end). The multiball_lock instead immediately replaces the locked ball by calling `self.source_playfield.add_ball(balls=balls)`and passing the number of balls it has physically locked. The `balls_in_play` count remains unchanged and the playfield ejects a ball from its default ball_device (the trough, almost always).

[This immediate replacement behavior](https://github.com/missionpinball/mpf/blob/dev/mpf/devices/multiball_lock.py#L274) cannot be prevented by any arguments or conditions. A physically locked ball will always and immediately be replaced via the source playfield's default ball device, which causes a bug.

**Consider the following setup:**
```
ball_devices:
  bd_lock:
    ball_switches:   s_lock_1, s_lock_2, s_lock_3
    ball_count:      3  # inferred by ball_switches, noted for clarity

multiball_locks:
  overlordlock:
    balls_to_lock:   3
    lock_devices:    bd_lock

multiballs:
  overlord:
    ball_count:      3
    ball_count_type: total
    ball_locks:      bd_lock
    start_events:    multiball_lock_overlordlock_full
```

The bug occurs when a `ball_device`, `multiball_lock`, and `multiball` are configured to physically fill up and begin a multiball, as above. When the third ball is locked the *multiball_lock_(name)_full* event is posted, which begins the multiball. HOWEVER, because of the replacement behavior noted above, the third ball lock *also* calls `source_playfield.add_ball(balls=1)`. The multiball [checks `balls_in_play` to know that one ball is currently in play](https://github.com/missionpinball/mpf/blob/dev/mpf/devices/multiball.py#L65) and therefore requests 2 balls to be ejected from its configured `ball_lock` device. 

The resulting behavior is a 3-ball multiball with 2 balls ejected from the lock device and 1 ball ejected from the trough. The expected behavior is that all 3 balls from the lock device are ejected to create the 3-ball multiball, with no balls are ejected from the trough.

**Comment by avanwinkle** [comment]
I've explored a number of approaches to solving this issue, and I cannot find any way around `MultiballLock._lock_ball` immediately and unconditionally replacing a locked ball (https://github.com/missionpinball/mpf/blob/dev/mpf/devices/multiball_lock.py#L274)

The lowest-impact solution I've come up with is an optional configuration setting that would allow a multiball_lock to replace a locked ball from its `lock_devices` device instead of the playfield's `default_source_device`.

#### multiball_lock.py Line 273:
```
# schedule eject of new balls for all physically locked balls
self._request_new_balls(balls_to_lock_physically)
```

#### Possible Fix:
```
if self.is_virtually_full and self.config['eject_on_full']:
  # schedule eject from self, effectively starting the multiball
  self._request_new_balls(balls_to_lock_physically, source_device=self.lock_devices[0])
else:
  # schedule eject of new balls for all physically locked balls
  self._request_new_balls(balls_to_lock_physically)
```

The configuration setting could be a boolean like the example above (`eject_on_full: true`), or it could be the name of the ball device to eject from (`eject_device_on_full: bd_lock`).

Thoughts?

**Comment by jabdoa2** [comment]
Interesting case. We definitely should write a unit test for that. The config above will not reset the lock count (unrelated to the bug). 

Alternativly, we can use a relay or boolean event and other devices can claim the ball. Similar to the ball_entered event in ball devices. The lock will only request a new ball when this one is not claimed. What do you think?

**Comment by avanwinkle** [comment]
Interesting. Looking into the claiming, the ball_device will retain and replace any balls that are claimed but eject any balls that are unclaimed, so if the multiball_lock were to *not* claim the final ball then the ball_device would eject it instead of replacing it. 

**Current:**
```
if self.is_virtually_full:
  self._events[device].append({'event': 'multiball_lock_' + self.name + '_full',
                               'balls': self.locked_balls})

self._request_new_balls(balls_to_lock_physically)
return {'unclaimed_balls': unclaimed_balls - balls_to_lock_physically}
```

**Without claiming:**
```
if self.is_virtually_full:
  self._events[device].append({'event': 'multiball_lock_' + self.name + '_full',
                               'balls': self.locked_balls})
  # Do not claim the last locked ball(s) to avoid replacing them
  balls_to_lock_physically = 0

self._request_new_balls(balls_to_lock_physically)
return {'unclaimed_balls': unclaimed_balls - balls_to_lock_physically}
```

Seems like this would have the same result in my situation, but I don't know what the repercussions would be across the board. It may be undesirable to prevent the multiball_lock from claiming the final ball, or could break other cases?

**Comment by jabdoa2** [comment]
This would be similar to ball_devices. If you claim a ball which entered a ball device the device will just keep it for you and you are responsible for ejecting it eventually. Similarly, if you claim a ball in a multiball_lock you are responsible for replacing it somehow. The multiball will take care of that by just ejecting the ball from the lock. So i guess it makes semantically sense.

**Comment by jabdoa2** [comment]
@avanwinkle: Do you want to work on this? Or should I prepare something?

**Comment by avanwinkle** [comment]
@jabdoa2 I'm happy to keep working on this, I haven't explored much with claimed/unclaimed balls so this will be a good opportunity for me to get more familiar with it. 

Thanks!

**Comment by avanwinkle** [comment]
Hey @jabdoa2, I've been looking into this multiball thing but I wasn't able to get the multiball to claim the unclaimed ball reliably because the multiball_lock was too eager to claim it first. It got messy when I tried to stop the multiball_lock from claiming the last ball by disabling the event listener, and it all went downhill from there.

So I've been thinking on other possible solutions, and here's one that might be flexible enough to support physical locks with multiple balls _without_ dramatically or forcibly changing other behavior.

As always, it comes down to this section of `multiball_lock.py`:
```
def _lock_ball(self, unclaimed_balls: int, device: "BallDevice", **kwargs):
        """Handle result of the _ball_enter event of lock_devices."""
        del kwargs
        # if full do not take any balls
        if self.is_virtually_full:
            self.debug_log("Cannot lock balls. Lock is full.")
            return {'unclaimed_balls': unclaimed_balls}

        # if there are no balls do not claim anything
        if unclaimed_balls <= 0:
            return {'unclaimed_balls': unclaimed_balls}

        capacity = self.remaining_virtual_space_in_lock
        # take ball up to capacity limit
        if unclaimed_balls > capacity:
            balls_to_lock = capacity
        else:
            balls_to_lock = unclaimed_balls

        balls_to_lock_physically = balls_to_lock

        for _ in range(balls_to_lock):
            self.locked_balls += 1
            # post event for ball capture
            self._events[device].append({"event": 'multiball_lock_' + self.name + '_locked_ball',
                                         "total_balls_locked": self.locked_balls})
            '''event: multiball_lock_(name)_locked_ball
            desc: The multiball lock device (name) has just locked one additional ball.

            args:
                total_balls_locked: The current total number of balls this device
                    has locked.
            '''

        if self.config['locked_ball_counting_strategy'] in ("virtual_only", "min_virtual_physical"):
            # only keep ball if any player could use it
            if self._max_balls_locked_by_any_player <= self._physically_locked_balls:
                balls_to_lock_physically = 0

        if self.config['locked_ball_counting_strategy'] == "min_virtual_physical":
            # do not lock if the lock would be physically full but not virtually
            if (self._physically_remaining_space <= 1 and
                    self.config['balls_to_lock'] - self.machine.game.player['{}_locked_balls'.format(self.name)] > 0):
                balls_to_lock_physically = 0
        elif self.config['locked_ball_counting_strategy'] != "physical_only":
            # do not lock if the lock would be physically full but not virtually
            if not self.is_virtually_full and self._physically_remaining_space <= 1:
                balls_to_lock_physically = 0

        # check if we are full now and post event if yes
        if self.is_virtually_full:
            self._events[device].append({'event': 'multiball_lock_' + self.name + '_full',
                                         'balls': self.locked_balls})
        '''event: multiball_lock_(name)_full
        desc: The multiball lock device (name) is now full.
        args:
            balls: The number of balls currently locked in this device.
        '''

        # schedule eject of new balls for all physically locked balls
        self._request_new_balls(balls_to_lock_physically)

        self.debug_log("Locked %s balls virtually and %s balls physically", balls_to_lock, balls_to_lock_physically)

        return {'unclaimed_balls': unclaimed_balls - balls_to_lock_physically}
```

The ball claim relay goes from ball_device -> multiball_lock and since the multiball lock has 1 more capacity, it "claims" the ball and physically locks it. The `_request_new_balls` method is called before the _multiball_lock\_(name)\_full_ event gets broadcast, so the playfield shoots a ball from the trough before the multiball (waiting for the _full_ event) has a chance to start ejecting from the ball lock. Same old story.

How's this for an idea: adding a config setting to `multiball_locks:` called **balls_to_replace**. Instead of just a boolean (like all of my previous proposals), this would allow the designer to have the `multiball_lock` always replace a locked ball (default/current behavior, `balls_to_replace: -1`), never replace a locked ball (`balls_to_replace: 0`), or replace locked balls up to _n-1_ of an _n_-ball multiball start (for a three-lock multiball, `balls_to_replace: 2`).

If the `multiball_lock` doesn't replace the last ball but knows its full, then the `multiball` can hear the _full_ event and start ejecting balls from the lock. It has the same effect as my initial proposals above, but with more flexibility for other scenarios.

**Comment by jabdoa2** [comment]
There might be a third way:

```
def _request_new_balls(self, balls):
    self.machine.events.post_relay("multiball_lock_{]_request_new_ball", callback=self._request_new_ball_callback, balls=balls, full=self.is_virtually_full)

def _request_new_balls_callback(self, balls, **kwargs):
    del kwargs
    self.source_playfield.add_ball(balls=balls)
```

The multiball could reduce the balls to 0 in the new relay event to prevent the eject and otherwise the balls would get ejected. Just a quick draft for your inspiration.

**Comment by avanwinkle** [comment]
Mmmm, a very interesting idea. I like the elegance of it, giving the `multiball_lock` the same behavior as currently but giving another device the opportunity to interrupt.

My first question is how the multiball would intercept it. Right now `multiball` and `multiball_lock` devices have no knowledge of one another, so we'd need some sort of event handler or config setting to tell the multiball to hook into the new relay event.

One option would be to add a config `multiball_lock` to `multiball` to tie them directly together. By default, the multiball could listen for its multiball_lock's  _request_new_balls_ and _full_ events, and automatically start when the lock is full (if the multiball is enabled). Possibly this setting could be used in lieu of the `ball_locks` setting (i.e. only one of them would be required). Also possibly, another setting `start_when_full: True` in case the designer wants to delay the start of the multiball after the multiball_lock is full.

Thoughts?

**Comment by jabdoa2** [comment]
I had the same question in mind yesterday when thinking about the event and came to a similar conclusion. Maybe something like: "start_on_full_multiball_lock" which would listen to the _request_new_balls event (we can rename that also) and just to everything right for this usecase.

In a lot of cases you don't want to start the MB instantly when the lock is full and those would still use different events to start the MB. However, starting on the full event does not make much sense. Maybe that one could become a relay event as well? So that the multiball could do the magic on the full event? Too much magic is usually not good but maybe it is ok in this case?

Just checked the code again and figured that we postpone all the events from the _ball_enter handler to the _ball_entered handler to prevent confusion in other devices about the real ball count in the device. So the idea above will probably cause other event order problems. Maybe this:

```
def _request_new_balls(self, balls_to_request, is_full):
    if is_full:
        self.machine.events.post_relay("multiball_lock_{}_locking_last_ball".format(self.name), callback=self._request_new_ball_callback,balls_to_request=balls_to_request, is_full=is_full)
    else:
        self._request_new_balls2(balls_to_request, is_full)

def _request_new_balls2(self, balls_to_request, is_full, **kwargs):
    del kwargs
    self.machine.events.post_relay("multiball_lock_{}_request_new_ball".format(self.name), callback=self._request_new_ball_callback, balls_to_request=balls_to_request, is_full=is_full)

def _request_new_balls_callback(self, balls_to_request, **kwargs):
    del kwargs
    self.source_playfield.add_ball(balls=balls_to_request)
```

That way we could start the multiball on the `multiball_lock_(name)_locking_last_ball` event. The handler would check if there is a `balls_to_request` variable and if yes set it to 0 (or max the number of balls in the MB). Then it could proceed to release or request the remaining balls.

**Comment by avanwinkle** [comment]
Sometimes it feels like we're going in circles 😛 

I spent some time yesterday working on the approaches described above, and intercepting/blocking events does get pretty magical but I found MPF getting confused a lot about how many balls were in play. I think I need to add a few more configuration options to `multiball` so it can have better control.

In a parallel track, I tried an option with no magic at all, just configuration settings. It's similar to some of what we've discussed above, but more flexible because the designer can control how many balls the lock auto-replaces and the multiball is not required to start at any time.

https://github.com/missionpinball/mpf/compare/dev...avanwinkle:multiball-lock-replace-strategy?diff=unified&name=multiball-lock-replace-strategy

This approach does everything needed and is fairly simple, at the cost of a misconfiguration leading to a stuck state. I would want to write a tutorial section for the docs explaining how to build multiballs for machines that lock physical balls.

I'd love any thoughts on that approach, while I continue trying out the events-based approach!

**Comment by jabdoa2** [comment]
We can merge that approach. I see no problem in doing that because it will only break if you configure it and people will not do that normally. I can also try to get the event based approach working if you want me to try.

**Comment by jabdoa2** [comment]
I thought about this some more. The ball count of the device will be updated when the _entered event is posted. What about this: We also postpone the relay event which will request new balls to the _entered event (similar to all the other events). That way all counts will be up to date and logic should be straight forward.

**Comment by avanwinkle** [comment]
The event based approach is still interesting, though when I tried to create a configuration setting for `multiballs` to hook directly into `multiball_locks`and behave properly. If you'd like to take a look I'd be interested in your approach, but I know you've got plenty of other things to work on and this situation seems to apply only to me :)
