### ISSUE TITLE
Support Servo Speed and Acceleration

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1086]
Expose speed and acceleration in servo config.
Pololu maestro supports that in hardware. Support it in software for other platforms.

**Comment by F4b1-** [comment]
Hi, I will take a look at this as my second issue. After reading the mpf documentation on the pololu mastro and looking at the code a bit it seem that the set_acceleration and set_speed methods are already implemented. So this is issue is just about parsing the speed/acceleration values from the config file and passing them on? Thanks!

**Comment by jabdoa2** [comment]
Yeah right. This issue is about adding it to config in a platform independent way (normalized values e.g. 0 to 1). Pololu supports it already. For other platforms we should emulate that but that part could also become a second issue.
