### ISSUE TITLE
Show machine and player variables in Text UI

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1119]
Show variables in the text UI. Show all by default. Make it configurable to always show certain vars on top (because space is limited)

**Comment by woosle1234** [comment]
I would like to try to implement this issue. Can you explain a bit more about what variables you want? and how do you want the configurable variables to work?

**Comment by jabdoa2** [comment]
Hi Woosle,

The idea is to show all machine variables (https://github.com/missionpinball/mpf/blob/dev/mpf/core/machine.py#L792) and player variables (https://github.com/missionpinball/mpf/blob/dev/mpf/core/player.py). Machine vars are generally accessible via self.machine.machine_var. Player vars are accessible (during a game only) via self.machine.game.player.vars. 

The text UI is rendered here: https://github.com/missionpinball/mpf/blob/dev/mpf/core/text_ui.py

**Comment by woosle1234** [comment]
So would that mean I would have to update the def _draw_player_header(self): in the text_ui.py and add in self.machine.machine_var and self.machine.game.player.vars. in there?

**Comment by jabdoa2** [comment]
Either there or in _update_player. There should be some space left there.

**Comment by woosle1234** [comment]
Is there a way to get all the variables for machine and player? I'm thinking of using a for loop or would I have to declare each name? Also is the documentation on the player and machine variables correct in listing all the variables?

**Comment by jabdoa2** [comment]
The documentation is mostly accurate but there might be more during running. I guess we could to add a getter for all machine variables and player vars. However, you could also loop over the variable i listed in my earlier post. That kind of bypasses the getter.

**Comment by jabdoa2** [comment]
fixed by #1328
