### ISSUE TITLE
Add additional parameters to multiball "shoot_again" config

### ISSUE THREAD

**Issue by fantasygoat** [missionpinball/mpf#1132]
The multiball "shoot_again" parameter should have similar fine-grained options to the regular ball save function:

active_time: 8s
hurry_up_time: 3s
grace_period: 2s

Then "multiball_X_shoot_again_enabled", "multiball_X_shoot_again_hurry_up" and "multiball_X_shoot_again_grace_period" events to trigger shows.

**Comment by atummons** [comment]
@jabdoa2 Can I go ahead and close this out?  This was in my pr #1590

**Comment by jabdoa2** [comment]
> @jabdoa2 Can I go ahead and close this out? This was in my pr #1590

Sure go ahead :-). Did not remember this issue at all.

**Comment by atummons** [comment]
Cool.  Didn't want to overstep my powers!  But closed in PR #1590
