### ISSUE TITLE
Drop Target and Drop Target Bank are overriding coils' default_pulse_ms with reset_coil_max_wait_ms.

### ISSUE THREAD

**Issue by kaydeeH** [missionpinball/mpf#1176]
In the reset methods for both drop targets and drop target banks, the config value 'reset_coil_max_wait_ms' is being sent to coil.pulse. Since 'reset_coil_max_wait_ms' defaults to 100ms if not explicitly set, this means that the reset coils's default value for pulse_ms is being overridden by this value (or its default). I have confirmed that if I set this parameter for a drop target bank, this is the ms value that is used to pulse the coil. Likewise, if I add this parameter but leave it's value empty, the coil.pulse will properly use the coil's default pulse ms value. Framework version 0.50.4.

**Comment by jabdoa2** [comment]
Good catch. That value should go into max_wait_ms. Feel free to issue a Pull Request if you want to solve it.

I will fix it tonight or tomorrow otherwise. Probably should add a test too.

**Comment by jabdoa2** [comment]
fix is in 0.50.9
