### ISSUE TITLE
Add configuration option to log in JSON format 

### ISSUE THREAD

**Issue by muffler-aus** [missionpinball/mpf#1177]
It would be nice to have JSON logging to enable better search filtering using tools like Splunk/ElasticSearch. I have created a patch that will give the -j command line option to enable JSON logging. Im not sure if this is the way you would like to have this option exposed but I guess with this issue and a PR we can start a conversation about how you would like it done.

**Comment by jabdoa2** [comment]
contained in 0.50.9

**Comment by jabdoa2** [comment]
this has been merged
