### ISSUE TITLE
Inconsistent Log Level in file log

### ISSUE THREAD

**Issue by avanwinkle** [missionpinball/mpf#1184]
A recent change (within the last few months) to logging behavior is unexpectedly hiding Event INFO logs from log files.

With the default log settings (i.e. "basic"), the MPF log file includes all INFO events and DEBUG events for devices with `debug: true` in their config. However, EventManager events are not displayed.

With the detailed log settings (i.e. "full" or `-v`) the MPF log file includes all INFO and DEBUG events for all devices. In this scenario, the EventManager events appear, although tagged as INFO.

I have attempted to adjust the levels in `logging.py` to get the file_info level above 20 and the file_debug level below 20 and this successfully gets the EventManager events into the INFO log. However on "full" mode, all DEBUG events show up as INFO.

I'm hoping this can be a quick revert by someone who understands the `self.__debug_to_file` and `self._info_to_file` logic better than I do.

**Comment by jabdoa2** [comment]
I guess this is configured here: https://github.com/missionpinball/mpf/blob/dev/mpf/mpfconfig.yaml#L144. Brian build that and i just made it work a few weeks back. We probably should change that setting to basic, right?

**Comment by avanwinkle** [comment]
Hey, that's great to know about! Configuring log levels on a per-device/mechanic level will be very helpful to me.

That said, I'm not sure I quite understand. In those defaults for `file:` it lists `event_manager: basic` yet it's in my log files that I'm not seeing any *EventManager* INFO events posted. In theory the INFOs should be logging to the file, if it's set to "basic" right?

**Comment by jabdoa2** [comment]
Yeah right. It should log info to file but not to the console.

**Comment by jabdoa2** [comment]
Should we change something in the defaults? Or leave it as it is?

**Comment by avanwinkle** [comment]
I was able to get my desired behavior by changing the logging level -> number conversions, making the INFO levels both >20 and the DEBUG <20. Currently, it's organized with Console >20 and File <20. 

https://github.com/missionpinball/mpf/compare/dev...avanwinkle:events-info-logging

This has addressed my issue of not seeing Event INFO logs in the log files, and I haven't identified any adverse side effects but I'm not too familiar with how `self._debug_to_console` et cetera are implemented, so my change may be breaking something else.

**Comment by jabdoa2** [comment]
I'm not that familiar with the area as well. I probably need to play with it myself. Will have a look. The confusion for me arises from having different logging targets.

Maybe we could simplify this? Set a limit/level per device (none, info, debug). Anything below that level will not be logged at all. Then set a limit for file and console. I guess that would be simpler and more clear. What do you think?

**Comment by avanwinkle** [comment]
I think it makes sense to have the config log levels correspond to the actual log levels, although since WARNING and ERROR are always logged there are still only two options. My main confusion comes from the console vs file distinction, because I don't see anywhere that different loggers are setup with corresponding levels. From my reading of the code, there is only one logger and it writes the same to file and console. Is the distinction only in the config `logging` section?

**Comment by jabdoa2** [comment]
I think so. I propose the following:

- Create a new option "log_level".
- Log file and console log will work like now (with -V and -v)

Would that work for you?

**Comment by avanwinkle** [comment]
I haven't explored much about the `logging` config options, I'll play with those some more and come up with a proposal for a "log_level" option that might help more generally than just in my case. Let's definitely keep the -V and -v options too. 

In the meantime, I'll make a PR for my fix on the 11/21 and 21/22 log levels to fix the bug of some INFO logs only showing up on DEBUG level.

Thanks for the help!

**Comment by jabdoa2** [comment]
fixed in #1197
