### ISSUE TITLE
Organize modes in subfolders

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1190]
Summary: I would like to be able to organize my modes inside the modes folder into sub-directories. This is not any type of show stopper, it would allow me to organize the game a little better.

currently, I have my modes organized like this:

/modes/base
/modes/high_score
/modes/band_gb_base
/modes/band_gb_rockfest
/modes/band_sq_firstavenue
/modes/band_sq_release

I would like to be able to organize them into subdirectories

/modes/base
/modes/high_score
/modes/band/gb/gb_base
/modes/band/gb/rockfest
/modes/band/sq/firstavenue
/modes/band/sq/release

From: https://groups.google.com/forum/m/#!topic/mpf-users/cZj5B8eiIZE

**Comment by pmansukhani** [comment]
Is this issue open for grabs?

**Comment by jabdoa2** [comment]
This one is open. Feel free to solve it.

**Comment by jabdoa2** [comment]
Fixed by #1396
