### ISSUE TITLE
Define default alignment for segment displays

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1201]
How should text align if it is shorter than the length of the display? Mypinballs aligns right. LISY to the left. Define and unify this

**Comment by avanwinkle** [comment]
For what it's worth, I think right-aligned makes more sense if we assume the primary use of segment displays is scores. In a fixed-width system, numbers should align right (and I feel like I see that more on machines in the wild). If it's not a number though, of course left-aligned makes sense.

**Comment by jabdoa2** [comment]
Yeah I agree. Right aligned should be the default. I talked to bontango (who develops the LISY platform) and he will change it. We could also change it inside the MPF platform but this way it will be probably a bit more flexible and MPF does not have to know how many characters the display has.
