### ISSUE TITLE
Make Ball Search for Ball Devices Configurable

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1204]
Currently MPF will eject ball from everything except a trough. Make this configurable

**Comment by dziedada** [comment]
Hi, is this still open?

**Comment by jabdoa2** [comment]
Hi @dziedada,

Yes this is still open. You can give it a go if you like. I suggest that you install MPF in dev in case you did not do that yet (http://docs.missionpinball.org/en/dev/about/contributing_to_mpf.html#install-mpf-in-development-mode). Here is a test for ball search in general: https://github.com/missionpinball/mpf/blob/dev/mpf/tests/test_BallSearch.py. The relevant code is here: https://github.com/missionpinball/mpf/blob/dev/mpf/devices/ball_device/pulse_coil_ejector.py#L80. Adding another tag would probably work. Alternatively, we could add an additional config option. Let me know if you have any questions!

Jan

**Comment by dziedada** [comment]
Hi @jabdoa2 ,

I was just getting started working on this, and it's not completely clear how configurable it should be. My current understanding is that is should be configurable in such a way that individual devices can be made to not eject balls. Is this correct?

Thanks, Adam

**Comment by jabdoa2** [comment]
Yes exactly. It should be possible to disable ball search for some devices. For example you might want to prevent it from ejecting balls from your ball lock (especially if there isn't any auto launcher).
