### ISSUE TITLE
Add setting to change high score order

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1257]
Currently, more is always better in highscore. Allow categories were lower is better (e.g. faster/less time).

Change this sort based on a config setting: https://github.com/missionpinball/mpf/blob/dev/mpf/modes/high_score/code/high_score.py#L151

**Comment by yensho** [comment]
Hi, I found this repo this afternoon, and would like to try contributing. Would it be alright if I took this issue?

**Comment by jabdoa2** [comment]
Hi yensho,

Contributions are welcome! There is some documentation about the process here: http://docs.missionpinball.org/en/dev/about/contributing_to_mpf.html. To get familiar with MPF try the tutorial here: http://docs.missionpinball.org/en/dev/tutorial/index.html.

Jan

**Comment by jabdoa2** [comment]
this has been solved in #1296
