### ISSUE TITLE
Minor improvements to Snux handling

### ISSUE THREAD

**Issue by Snux** [missionpinball/mpf#1268]
Too much of a noob to do this myself yet!

There are a couple of changes to the Snux code that would make sense, but one is a single liner so I'll include them both here.

Easy one - this line should use number.lower().endswith('a') - like it already does for 'C' coils.  Otherwise if you label coils with an uppercase 'A' then they don't get processed.

https://github.com/missionpinball/mpf/blob/cb18f4da4ce7d281dbe234614799b346a14301d1/mpf/platforms/snux.py#L143

The other one would make things tidier but wouldn't break existing config.  If someone has their coil platform as 'snux', any coil without an 'A' or 'C' suffix really doesn't need to be handled this way.  In this case it would make sense to default the platform back to whatever the main one is (p_roc, FAST or whatever).  That way I don't need to put "platform: p_roc" on half my coils to make autofire etc available.  It should also mean that changing platform to smart_virtual won't give me errors for the coils which are looking for p_roc.

**Comment by jabdoa2** [comment]
The first one is easy. Will apply that change.

The second thing is a bit tricky but I get why you want that. Does that also cause problems when you switch to smart_virtual using the -X option in the command line?

**Comment by jabdoa2** [comment]
Your fix is here: https://github.com/missionpinball/mpf/commit/63cee50d2cd816565a8173b162c58135ddb9cc36

**Comment by Snux** [comment]
The main reason for trying to run with platform of smart_virtual was because I couldn't get both my matrrix displays to show in my on screen window, so I wanted virtual except for the matrix displays.  Now that I've got that working, running with -X works, so this "enhancement" for the A/C should be really low on the priority list now.

**Comment by jabdoa2** [comment]
closing this for now
