### ISSUE TITLE
System 11 A/C reverse logic

### ISSUE THREAD

**Issue by Snux** [missionpinball/mpf#1283]
Not brave enough to clone and fork yet, but I'll document the issue and fix here.

The A/C relay logic is working in MPF, however by default it sits with the relay disabled, ready to process  drives on the 'A' side.  Actually Sys11 does this the other way around, at rest the relay is energised ready to service the 'C' side.  The reason for this is that 'C' side is normally flasher lamps that need a quick response so shouldn't wait for the A/C relay to switch first.  'A' side is normally coils for ejects and things, and they can wait for the relay to switch first.  I also verified this behaviour with pinmame.

The fix is quite simple in snux.py - a new declaration for a_side_active and then reverse the logic in the final line of the tick.  I've made the change on mine and tested it, works just fine.  I attach the updated whole file, can someone get this merged?

[snux.zip](https://github.com/missionpinball/mpf/files/2727493/snux.zip)

**Comment by Snux** [comment]
Actually, it probably needs to be more clever than this, I'll do some more investigation.

**Comment by jabdoa2** [comment]
I guess we could also rewrite the logic in asyncio to make this code better readable. Your change definitely makes sense. I will merge it once you are done

**Comment by Snux** [comment]
Actually I've been checking more closely what the original code does via pinmame.  When a ball is in play, it "prefers" the C-side, so generally the relay is enabled for faster flasher response.  When there is no ball in play, it "prefers" the A-side so the relay is generally switched off (no need to keep it energised if not needed I guess).   So the snux logic probably needs to have a preference too which we can change on some event.

I'll add some event handling into the snux code (prefer_a_side and prefer_c_side) and get it working, then will drop you a note to see the best way to integrate this properly.

I've also just read that later Sys11 machines also have a switch on the matrix which activates when the A/C relay is active, so the machine can be sure that it's working.  I don't have a machine with this though so have no way of testing it.  Adding this to MPF someday is a nice to have, it just adds an extra level of security.
