### ISSUE TITLE
No widget removed event

### ISSUE THREAD

**Issue by cfbenn** [missionpinball/mpf#1332]
MPF has no event to signal when a widget has been removed.

An event should sent when a widget is removed following similar to logic when the slide_(name)_removed event occurs (but for a widget).

**Comment by qcapen** [comment]
Along with mpf_mc PR 372, adds optional custom events for widget added and widget removed events using new widget properties events_when_added and events_when_removed.

**Comment by qcapen** [comment]
Implemented in dev (0.53).  Docs have been updated as well (dev).
