### ISSUE TITLE
Refactor machine variables into separate class

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1375]
Currently, machine vars are in the main MachineController. Move them to a member "variables" so that they can be accessed as `self.machine.variables.get("name")` or `self.machine.variables["name"]`.

**Comment by evilmopey** [comment]
Is it all right if I try to solve this Issue?

**Comment by pmansukhani** [comment]
@evilmopey Are you working on this?
@jabdoa2 Can I take this up?

**Comment by jabdoa2** [comment]
You can totally work on this one.

**Comment by pmansukhani** [comment]
@jabdoa2 Does this include refactoring classes and tests where the machine vars are accessed as `self.machine.get_machine_var` OR would those functions use the new class under the hood? 

Do the functions `configure_machine_var`, `set_machine_var` need to be refactored as well?

P.S.: Although I'm an experienced developer, I'm very new to Python and open source. Really appreciate your help.

**Comment by jabdoa2** [comment]
@pmansukhani the general idea is to refactor all methods related to machine variables into a separate class and change all callers. It might be possible to use a refactoring feature of an IDE such as PyCharm to perform the move. Should be three or four methods. At the end all unit tests should (still) pass. Test coverage should be very good in this area.

**Comment by jabdoa2** [comment]
fixed in #1394 by @pmansukhani
