### ISSUE TITLE
Move parse_conditional_template out of players

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1391]
Parsing should be done when loading the player not during runtime. Move all calls to load time.

**Comment by avanwinkle** [comment]
Is this issue referring to specific players or specific conditional template calls?

There is much value in runtime parsing of conditions, when a triggering event may determine which sound to play or slide widget to show. I personally use conditional templates abundantly, as one templated value saves me a dozen individual listeners.

**Comment by jabdoa2** [comment]
It refers to all players which parse conditional templates. I want to keep current behavior. Currently we are reparsing "your_event{conditon > 3}" every time your player runs. String parsing is expensive (especially with a regex). For now I just added lru_cache to parse_conditional_template because the output will never change. As a long-term solution parsing should happen when we instantiate the player. Evaluation of the template will still happen at the exact same time.
