### ISSUE TITLE
[doc] improve raspberrypi / apigpio documentation

### ISSUE THREAD

**Issue by arthurlutz** [missionpinball/mpf#1428]
It would be nice to have a bit more detail in the raspberrypi documentation. 

Am willing to contribute towards this if I get something working. 

For example, does another process need to be started for apigpio to run on port 8888 or is it mpf that starts it ? Maybe also an example (if possible) where mpf is running on a PC and a raspberrypi runs apigpio on the network.

**Comment by jabdoa2** [comment]
We are using pigpio on the RPi side: http://abyz.me.uk/rpi/pigpio/pigpiod.html. MPF works as long as it can connect to pigpio. Please also note that pigpio does not support hardware rules like other pinball platforms.

**Comment by jabdoa2** [comment]
Thanks for the docs improvements!
