### ISSUE TITLE
Detect missing curly backets in conditional events

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1497]
MPF will currently not complain about missing closing curly backets in conditional events. Detect strings as the following as error:

`update_multiplier_symbols{current_player.multiplier_bonus<2: multiplier_symbol_bonus_fadeoff`

Discussion: https://groups.google.com/forum/#!topic/mpf-users/aSTxHNctUdM

**Comment by seanirby** [comment]
Looking for a lightweight first issue so I can get my mpf dev environment set up and start contributing.  This one looks pretty good!  I still don't understand the project structure but I was going to try and replicate Sebastian's issue, find where the YAML parsing happens, and add a try/catch around it along with a helpful error message.  Can you give me an idea of what you had in mind to fix this?

**Comment by jabdoa2** [comment]
This function should handle it correctly: https://github.com/missionpinball/mpf/blob/dev/mpf/core/placeholder_manager.py#L785. I guess I would add a test first and then try to fix the underlying problem in that function. The code is called from here: https://github.com/missionpinball/mpf/blob/dev/mpf/config_players/event_player.py#L29. Let me know if you want to know anything else.

Looking at the code there are also a few ways to optimize this in case we run into perf problems because of template parsing. But that's not part of the issue here.

**Comment by jabdoa2** [comment]
I fixed this a bit more generically. PlaceholderManager does not capture this and it tries to register an event with unbalanced brackets it will throw an error. However, there might be cases where it would make sense to fix this in PlaceholderManager as well if you still want to work on it.

**Comment by seanirby** [comment]
Haha perfect timing, I got my dev environment set up just now to look at this.  I'll find another issue.
