### ISSUE TITLE
Changelog for 0.54

### ISSUE THREAD

**Issue by avanwinkle** [missionpinball/mpf#1538]
Here's a tracker for what's going into 0.54, which should probably be released before it gets too big 😄 

This first pass is based on the git diffs between `dev` and `0.53.x`. I'll do another pass through the commit history, PRs, and forum posts to check for anything I missed, then call out potential breaking changes separately.

### Features
* Batched lighting updates for supported platforms
* Delayed pulse-on-hit rule (for supported platforms)
* Error codes for many common errors, especially config file errors
* Flipper EOS support for both with and without hold coils
* [x] Glow effect for MC displays @seanirby 
* [x] High Scores can now be reset
* Initial support for Python 3.8 (only MPF; Kivy in MPF-MC still only supports up to Python 3.7)
* MPF-MC Interactive mode debug dump
* New default ball search behavior
* New prepackaged font option *DSEG14Classic-Italic*: a 14-seg font similar to System 11 displays @seanirby 
* [x] RandomEventPlayer now supports conditional events in the event list
* Pin2DMD support for RBG lights and 192x64 displays
* P-ROC support for GPIO interface
* [x] Production-optimized code packaging for making non-dev builds
* [x] ShowPlayer queue support for deferred sequential playback
* [x] ShowPool configuration for pooling shows like other assets
* [x] Sequential light loading for simplified light chain addresses
* Separated config loading and parsing to prevent race conditions and improve references
* Serial LED support for OPP
* Service mode now includes Audits, Adjustments, and Utilities menus by default
    * **Breaking Change** Diagnostics menu (switch, coil, light) is now a sub-menu
* Twitch client integration @mwseiden 
* Visual Pinball Engine support (not part of the release as it is unfinished)

### New Config Options
* [x] Accrual `advance_random_events` to advance an accrual block randomly
* [x] Bonus mode `keep_multiplier` setting now supports conditions
* [x] Carousel mode `block_events` and `release_events` to prevent accidental selection changes with flipper press + flipper cancel
* [x] DropBank `ignore_switch_hits_ms` to prevent switch counting when the bank resets
* [x] LightPlayer now accepts a `key` argument to track specific instances
* [x] RandomEventPlayer `fallback_event` to play if all listed events are conditional and none evaluate true
* [x] Show `start_running` boolean to play the first step of a show and immediately pause it
* SoundLoop `loop_start_at` and `loop_end_at` times @qcapen 
    * ⚠️ The config docs reference `start_loop_at` which is consistent with `end_loop_at`
    * The MC code and config_spec reference `loop_start_at` and don't have `start_loop_at`
* [x] TextInput `block_events` and `release_events` to prevent accidental inputs with flipper press + flipper cancel

### Bug Fixes & Behavior Improvements
* **Breaking Change** Deprecated `ball_locks` device (use `multiball_locks` instead)
* **Breaking Change** Deprecated space-separated lists—use comma-separated lists instead (with or without spaces)
* **Breaking Change** Deprecated switch `playfield_active` tag—switches no longer need this
* **Breaking Change** MPF will complain on event handlers with the same name as a switch. This should not happen in practice and has been done to catch typical user error (i.e. using the event ``s_my_switch`` instead of ``s_my_switch_active``). 

* BCP event handlers for active mode change events 
* Fixed StateMachine bug that prevents MPF Monitor from connecting 
* Fixed issue with `#` character in config values @seanirby 
* Fixed VPX `set_fade()` function for consistency with other platforms @Wolfmarsh 
* FlasherPlayer now defaults to "on" to play default color, instead of "white"
* Lazy-load zip image pools
* Improved messaging and context for errors
* Improved motor device to track last known position and prevent undesired moves
* Improved support for additional priority in conditional events
* Improved support for fade configuration in lights
* Support for Stern Spike 2 platforms
* Improved switch hit timing detection for timed switches and delay/ignore windows
* Prevent crash on credits counter when encountering corrupted data
* Prevent adding new players during ball/game end @seanirby 
* Prioritized loading of `named_colors` before mode config validation

### Other
* Automated methods to create and read yaml templates
* Improved type documentation across the codebase
* Major refactor of config file validation
* Many new and improved tests
* New assertions for platform feature support
* New compiled pinproc libraries for Windows @qcapen 
* Performance improvements for event handling
* Refactored BallDevice validation for specific switch, counter, and ejector devices
* `Util.string_to_event_list` method for specifically parsing event lists
    * Config spec supports types `event_handler` and `event_posted` for better validation

**Comment by jabdoa2** [comment]
Guess it's time for a release. General state of mpf should be good. I don't see any open issues. I probably want to remove the VPE platform as it is incomplete from the release (but keep it in dev). Other than that I don't think we got any unfinished features laying around.

**Comment by avanwinkle** [comment]
I noticed an issue with the sound loop player: the docs have been updated with an option `start_loop_at`, which matches the convention of `end_loop_at`, but the code itself uses a config setting `loop_start_at`. @qcapen perhaps you can advise?

**Comment by qcapen** [comment]
@avanwinkle thanks for noticing that discrepancy. I've fixed the docs to reflect the final implementation (I believe I changed the names after the first code commits and I had already written the documentation).

**Comment by jabdoa2** [comment]
0.54 has been released
