### ISSUE TITLE
Fix: If different version of ruamel.yaml is installed on user's workstation than version 0.15.100, mpf will throw VersionConflict error

### ISSUE THREAD

**Issue by johnblat** [missionpinball/mpf#1618]
**why**
user may have a site installed package for ruamel.yaml that is on the most recent version (or another version)

**Installer used **
Debian installer 0.55.x

**OS identified on**
Ubuntu 20.04

**how to reproduce**
pip install ruamel.yaml
That should install the latest version available.
download the mpf installer.
./install
mpf --version
error:

`
Traceback (most recent call last):
  File "/usr/local/bin/mpf", line 8, in <module>
    sys.exit(run_from_command_line())
  File "/usr/local/lib/python3.8/dist-packages/mpf/commands/__init__.py", line 177, in run_from_command_line
    CommandLineUtility(path).execute()
  File "/usr/local/lib/python3.8/dist-packages/mpf/commands/__init__.py", line 116, in __init__
    self.get_external_commands()
  File "/usr/local/lib/python3.8/dist-packages/mpf/commands/__init__.py", line 124, in get_external_commands
    command, function_ref = entry_point.load()()
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2463, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2486, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (ruamel.yaml 0.17.4 (/home/<user>/.local/lib/python3.8/site-packages), Requirement.parse('ruamel.yaml==0.15.100'), {'mpf'})

`

**how to fix**
pip install ruamel.yaml ==0.15.100
mpf --version
It Works!

**possible solutions**
- encourage user to use virtual environment
- Don't be as specific about which version of ruamel.yaml to use
- Others?

**Comment by jabdoa2** [comment]
>     * encourage user to use virtual environment

Good plan. Any idea where we should emphasis this more in the docs? Venv will save you most of the times.

>     * Don't be as specific about which version of ruamel.yaml to use
Unfortunately, that caused issues in the past because newer versions dropped support (wheels for windows) for older python versions. So not really an option.

**Comment by johnblat** [comment]
I see this: https://docs.missionpinball.org/en/latest/install/linux/index.html#yaml-error-on-first-start

I think mention the error will also occur if a different version is already installed on the system. And then after that explain that the user can either install over it or create a virtual environment to have the two versions coexist, and provide a link to the python docs on virtual envs.

**Comment by jabdoa2** [comment]
Good find! Do you want to create a Pull Request for the docs?

**Comment by johnblat** [comment]
sounds good to me. I'll write it up tomorrow

**Comment by johnblat** [comment]
forgot to close this out. I submitted a PR with the info added to the docs a while ago
