### ISSUE TITLE
Launch process needs some love

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#166]
Currently the launching process is a bit rough.

It should know whether a process (either core or mc) was launched in a separate console window or not, and only pause the output (Press any key to exit...) if it was a new window.

Also `mpf both` should be changed to be platform specific since it's impossible to write a single python script that works for all platforms.

In general the whole process needs to be cleaned up a bit.

**Comment by Lamoraldus** [comment]
- It would be nice if the game could reconnect after a kill and restart to a running mc. Maybe resetting the mc to have a clean starting point.
- As the game has to wait for the mc to start, maybe the mc could spawn the game after it is running?
- The „press any key to exit“ is only needed on platforms that close the process’ window on exit. If you open the shell yourself that should never happen. The default should be no message. You could add a parameter like -w (wait) to enable that message.

**Comment by toomanybrians** [comment]
Also make sure both mpf and mc retry to connect forever

**Comment by toomanybrians** [comment]
love made.

Fixed @Lamoraldus bullet points 2 and 3. 1 will have to wait until 0.31.
