### ISSUE TITLE
number_grouping group_digits does not work with negative numbers

### ISSUE THREAD

**Issue by JAMESCARDONA-PINBALL** [missionpinball/mpf#1683]
title says it. When a text widget is flagged as number_grouping: True and a negative number is passed, then the number_grouping does not work. That is, if the number is large the commas are not inserted as they should be. This code appears to be in mpfmc in text.py under group_digits function

**Comment by atummons** [comment]
FYI I'll tackle this one in the next week or so. In the current code "-123" is not a digit, as only numbers are digits. So we can swap to check if it's an int (or float if we need decimals, but currently only whole numbers are covered - so I'll keep it to that). Then it'll keep the negative sign and swap back in the properly grouped number.

**Comment by toomanybrians** [comment]
closing this since this is an MPF-MC thing and @atummons created the tracking issue there. Thanks everyone!
