### ISSUE TITLE
Write a config validator for shows

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#175]
Currently individual player sections in shows are validated, but the overall shows are not. So sections that are mis-named, or stray sections, empty sections, wrong indents, and general malformed stuff can crash MPF in fun ways.

**Comment by toomanybrians** [comment]
check to make sure shows are lists and not dicts, maybe look for other examples of failures?

**Comment by jabdoa2** [comment]
this is no longer true. most (if not all) areas are validated
