### ISSUE TITLE
Fast LEDs in 0.56.2 are behaving the inverse of their type (GRB=RGB, RGB=GRB)

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#1754]
I think there's a bug in MPF 0.56.2 that is treating all LEDs as GRB. Steps that I've taken to isolate this include:

Direct serial commands to FAST RGB processor. RA:FF0000 to a FAST LED turns the them red (and it turns the real GRBs in my game green)

In MPF, I have a minimal config set up that I'll paste in below. Just a few test lights...just enough config to get the game to start and turn them all on. 

LEDs that are set to red will turn green regardless of whether they're RGB or GRB. To put it another way, setting any LED to FF0000 will turn it green.

As expected, 00FF00 will turn them red, and 0000FF will turn them blue.

The only way I can make a regular FAST RGB LED turn red with FF0000 is to put type: grb in config for each light. And the only way I can make a GRB LED turn red with FF0000 is to change its type to RGB.

Finally, Monitor is not a good test for this because it follows the config properly. Because of that, I suspect the problem is in the platform driver. 

Here's the minimal config (from Brooks n Dunn):

#config_version=5

hardware:
  platform: fast
  driverboards: fast

fast:
  ports: /dev/FASTnet, /dev/FASTrgb
  rgb_buffer: 10
  hardware_led_fade_time: 65ms
  console_log: full                                                               

modes:
  - attract

lights:

  # Regular FAST LEDs that are NOT RGB
  l_australia:
    number: 1-0
    tags: right
    default_on_color: ff0000
 
  l_south_america:
    number: 1-7
    tags: right, right_ramp, jackpot
    default_on_color: ff0000
  
  l_again:
    number: 1-13
    tags: center
    default_on_color: ff0000

  l_shoot:
    number: 1-14
    tags: center
    default_on_color: ff0000
    type: grb

  l_world_tour:
    number: 1-20
    tags: center
    default_on_color: ff0000
  
  l_north_america:
    number: 1-32
    tags: left, left_orbit
    default_on_color: ff0000
  
  l_europe:
    number: 1-38
    tags: center
    default_on_color: ff0000
  
  # WS2811 RGB Chain that is GRB
  l_gi_right_5:
    number: 2-0
    tags: gi, gi18
    type: rgb
   
  l_gi_right_4:
    number: 2-1
    type: rgb
    tags: gi, gi19
   
  l_gi_right_3:
    number: 2-2
    tags: gi, gi20
    type: rgb
    
  l_gi_right_2:
    number: 2-3
    tags: gi, gi21
    type: rgb
   
  l_gi_right_1:
    number: 2-4
    tags: gi, gi22
    type: grb
  
  l_gi_left_2:
    number: 2-5
    tags: gi, gi2
    type: grb
   
  l_gi_left_1:
    number: 2-6
    tags: gi, gi1
    type: grb
 

shows:
  _overwrite: true
  all_lights_on:
    - duration: -1
      lights:
        gi: ff0000
        left: ff0000
        right: ff0000
        center: ff0000

show_player:
  mode_attract_started: all_lights_on

**Comment by Wolfmarsh** [comment]
This issue has existed for a long time, and I was told it was correct.   I don't know if that's the case or not.  But I would be careful about switching this up on people that have games out there.

**Comment by GabeKnuth** [comment]
Thanks. I won't switch - I think it's my problem alone. I assumed my config was good, but something big changed in how lights are addressed. I'll close this and reopen if necessary.
