### ISSUE TITLE
Starting mode with use_wait_queue regression since v0.57.1.dev3

### ISSUE THREAD

**Issue by mrechte** [missionpinball/mpf#1787]
Hello,

Not sure but since recent commits, a mode that used to be started with use_wait_queue: true, now seems to ignore it:

Before:
`2024-03-24 16:03:06,275 : INFO : EventManager : Event: ======'mode_ball_end_started'====== Args={'queue': <QueuedEvent>}
`
Now:
`2024-03-28 16:22:58,808 : INFO : EventManager : Event: ======'mode_ball_end_started'====== Args={}`

**Comment by mrechte** [comment]
I reverted to dev32, and problem is still here. So it is a config error, not MPF.

**Comment by avanwinkle** [comment]
Thanks for the note, if you do find any regressions in MPF let us know so we can add some more tests to catch them in the future!
