### ISSUE TITLE
Replace delays & delay manager with clock schedules?

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#213]
I'd be interested in getting opinions on this, but since MPF now uses the Clock based on Kivy's clock which has schedule_once() and schedule() methods, I wonder if we should remove MPF's Delay (and related) classes and code and switch everything to Clock schedules?

We'd have to check to see where those land in the tick process, and to make sure that the way we use multiple delay managers can be ported over. Also a callback returning False to a Clock schedule will remove that schedule, so we'd have to look out for that.

But if we can make this work, that would be a big chunk of code in MPF we can get rid of....

**Comment by jabdoa2** [comment]
Is DelayManager more than a thin wrapper? Maybe we can just make it thinner?

In my opinion, it would be more important to make MPF tickless for normal delays. Currently, all delays wait until the next tick to get executed. But why? In my opinion, this is only needed in mpf-mc. We should make MPF as responsive as possible. Of couse, tick functions with periodic tasks (such as updating LEDs) can still use schedule() with a fixed period.

**Comment by jabdoa2** [comment]
I think this i fine how it currently is.
