### ISSUE TITLE
FAST DMD flicker

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#229]
The DMD on the FAST Core and WPC controllers via the 14-pin connection flickers. On hold pending a firmware update. Worst case I'll fix this when I'm in Seattle with Dave for the NW show.

**Comment by jabdoa2** [comment]
@toomanybrians should we close this? Probably an flow control issue

**Comment by toomanybrians** [comment]
I think this is the same problem we had with the SmartMatrix DMD in October which you fixed (I forget how.. maybe asyncio?) So we just have to make the FAST mono DMD code work like the smartmatrix dmd code.

**Comment by jabdoa2** [comment]
this seems to work fine.
