### ISSUE TITLE
Implement checks for FAST triggers & board location

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#233]
FAST I/O boards can only program hardware rules "locally" within the board, e.g. the switch and driver must be on the same board.

The exception is switches 00-07 (which are the first switches on whichever board is connected first in the loop to the controller). Those switches are put in a priority packet on the loop network for minimal latency and sent to all other boards immediately.

The idea is those are typically flipper buttons which would be in an I/O board in the cabinet controlling drivers on an I/O board under the pf. Otherwise this is typically a non-issue, since for example a pop bumper switch and coil are near each other and can be plugged into the same board no prob.

So I want to implement checks in the FAST platform to ensure that hw rules are set only with switches that are on the same board as their drivers, with the exception of switches 00-07 which can control any driver.

**Comment by jabdoa2** [comment]
fixed in dev
