### ISSUE TITLE
allow_enable and timed_enable

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#237]
When pulsing a coil with more than 255ms pulse time we fall back to timed_enable for most platforms. However, this raises an error if the coil does not have allow_enable set.
- Should this work?
- Or should we just improve the error message?

**Comment by toomanybrians** [comment]
I think we should still respect allow_enable, and then make a better error to explain that they have to set allow_enable if they want to pulse for more than 255ms?

Also, unrelated, I think I want to make error numbers for mpf which we can then link to with more details? So we can just make up the numbers, starting with 1, but something like "Error: 1, see docs.missionpinball.com/errors/1 for details" Then we can explain things in full?

**Comment by jabdoa2** [comment]
Makes sense. Also there are some error messages which can be improved to be better understandable.

**Comment by jabdoa2** [comment]
fixed and tested in dev
