### ISSUE TITLE
Allow tests to ignore unrecognized show sections

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#276]
The reason the mpf-examples tests are commented out in mpf's travis.yml is because they fail due to the `slides:` section being in the demo_man attract mode dmd show. This is because the slides section is not valid unless mpf-mc is also installed since the plugin players are used to validate shows. (config files don't need plugins to validate currently since all config file sections, even those from mpf-mc, are in the config validator)

So we either need to (1) install mpf-mc before we run the demo_man test, or (2) change the MpfMachineTestCase to overwrite the show validation so it ignores unrecognized show settings instead of raising an exception.

The downside of installing mpf-mc is that since travis is linux it would have to build, which will add about 6 minutes to the tests.

thoughts??

**Comment by jabdoa2** [comment]
See #278. Should be fine for those tests.
