### ISSUE TITLE
Why are we ignoring hold in config_play_callback

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#284]
In led_player and light_player

**Comment by toomanybrians** [comment]
good question. When I refactored to use keys, I didn't include hold because I thought that would be set in the show or something.. I dunno. oversight. I'll take on adding this back in.

**Comment by toomanybrians** [comment]
moving to 0.31

**Comment by toomanybrians** [comment]
Moving this back to 0.30. We need to fix this.

**Comment by toomanybrians** [comment]
done
