### ISSUE TITLE
Did the tilted attribute vanish?

### ISSUE THREAD

**Issue by Lamoraldus** [missionpinball/mpf#320]
AttributeError: 'Game' object has no attribute 'tilted'

That was used in bonus.py like this:
```
  def mode_start(self, **kwargs):
    if self.machine.game.tilted:
      self.stop()
```

**Comment by toomanybrians** [comment]
Yes. It wasn't used by MPF so we removed it. Since you had it in a custom mode code, you can just comment out these lines.

We will soon do a small refactor of the way tilt works which will actually implement this functionality. Should be done in a few days.
