### ISSUE TITLE
Fix pinproc driver for x64 Windows

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#328]

**Comment by qcapen** [comment]
I've spent a lot of time analyzing the Visual Studio projects for pypinproc and pinproc and cannot find any way to resolve this issue.  The pinproc project includes ftd2xx.h and is not linked with any ftdi libraries.  Pypinproc incorporates the pinproc library and is linked with ftd2xx.lib.  The x64 version is linked with the ftd2xx.lib in the amd64 subdirectory of the ftdi installation while the 32-bit version is linked with the ftd2xx.lib in the i386 subdirectory.  In both cases the library has the same name.  There is no place in the code or project settings where the dll used at runtime (ftd2xx.dll) is specified.  The ftd2xx.lib library must be controlling the loading of the actual dll so I do not see anyway to force it to use ftd2xx64.dll.  

I'm open to any suggestions, but I cannot find a solution other than renaming the ftd2xx64.dll to ftd2xx.dll and putting it in the path.

**Comment by jabdoa2** [comment]
Why does just installing the driver to windows folder not work? I mean that should be the same on all windows versions right?

**Comment by toomanybrians** [comment]
Here's a thread about this: https://missionpinball.com/forum/topic/how-install-ftdi-drivers/

**Comment by toomanybrians** [comment]
I'm fine with the rename and to put it in the path. I'll add that into the docs and make it official.
