### ISSUE TITLE
"mpf both" doesn't work on Mac OS X

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#358]
it seems that both processes start, but the BCP channel is not actually established or something

**Comment by brian90254** [comment]
I did a manual edit to "both.py", and adding the line 'time.sleep(10)' before kicking off the 'game' command did the trick most of the time. So it's pretty clear that the arguments are being passed correctly, and the commands are being executed correctly.

So, as you noted, seems like something to do with the BCP being established. I think this is probably the case with OSX in general, meaning if you started 'game' first, or started 'mc' and 'game' simultaneously, you would also have this problem.

Maybe is OSX the 'game' thread is not doing a "re-try" correctly?

BC

**Comment by jabdoa2** [comment]
we clearly have socket problem here. @brian90254 can you try my "tickless_mpf" branch (future 0.31)? I reworked the socket handling there.

**Comment by toomanybrians** [comment]
fixed in 0.30
