### ISSUE TITLE
Tokens for RGB with fade 'express config' not working as expected.

### ISSUE THREAD

**Issue by BrewinBombers** [missionpinball/mpf#371]
When using tokens in shows in combination with fades in express configuration format, MPF throws an error:

_AssertionError: Invalid RGB string: (secondcolor)_

**Offending Code:**

`- time: +20ms
 leds:
   l_drain: (secondColor)-f500ms`

**QDog says:**
" Found the problem in the code.  You can simply comment out line 68 in mpf\config_players\led_player.py (`RGBColor(RGBColor.string_to_rgb(composite_value[0]))`). This check will not work with tokens and is not used when a fade is not present."

**Comment by BrewinBombers** [comment]
Have confirmed that QDog's comment produces the desired result.

**Comment by qcapen** [comment]
Fixed.  Waiting for pull request to be completed.
