### ISSUE TITLE
Create registry of previously registered BCP register_trigger events

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#467]
The problem is that if the BCP.register_trigger() meth is called, it's just sent to all connected BCP clients. But if a new client connects, it doesn't get the registered events.

Solution proposed is to make that meth keep track of the set of events, and then also whenever a new BCP client connection is made, to resend all the currently registered events.

Should probably create a deregister_trigger while we're at it

**Comment by jabdoa2** [comment]
On MPF side a trigger is per client. Should be enough to fix this on the mc side
