### ISSUE TITLE
Mode Lifecycle

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#479]
Extend the mode lifecycle and define events around it. One atomic event per transition and a queue event before/after the transition.

States: not running -> starting -> running -> stopping -> not running

Events:
- mode_will_start, we setup config players here, devices, etc.
- mode_starting (queue), mode configs and config players can hook this
- mode_started (like before), enable devices
- mode_will_stop
- mode_stopping (queue), mode configs and config players can hook this
- mode_stopped

**Comment by qcapen** [comment]
Implemented in 0.50
