### ISSUE TITLE
Game Lifecycle

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#480]
Extend the game lifecycle and define events around it. One atomic event per transition and a queue event before/after the transition.

States: not running -> starting -> running -> starting_ball -> play -> ending_ball -> (...) -> stopping -> not running

Events: (TODO: look up previously existing events and add them)
- player_will_add/adding/added (parameters: player_num, late_add_in_game)
- game_will_start
- game_starting (queue)
- game_started
- player_turn_will_start/ing/ed (parameters: player_num) 
- ball_will_start (parameters: player_num, ball, player_change, is_extra_ball, opt: extra_ball_num_in_game, extra_ball_num_in_ball) 
- ball_starting (queue)
- ball_started
- ball_will_end (parameters: player_num, ball, player_will_change, next_will_be_extra_ball) 
- ball_ending (queue)
- ball_ended
- player_turn_will_stop/ing/ed
- game_will_stop
- game_stopping (queue)
- game_stopped

**Comment by qcapen** [comment]
The following events have been removed in 0.50 and will need to be migrated:

- player_turn_start (replaced with player_turn_will_start or player_turn_started)
- player_turn_stop (replaced with player_turn_will_end, player_turn_ending, player_turn_ended depending upon how event was used)
- player_add_success (replaced with player_added)

**Comment by qcapen** [comment]
Implemented in 0.50
