### ISSUE TITLE
Add shot for simultaneous switches

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#517]
This came from the idea of wanting a way to do a "flipper cancel" for bonus, cut scenes, etc. Originally I thought we could post an event when both flippers were active at the same time, but why reinvent the wheel?

Let's add an option to shots where you can specify a shot based on two or more switches being active at the same time. That way we could create a "flipper_cancel" shot and the game could simply enable it when it wanted to watch for it.

**Comment by GabeKnuth** [comment]
I think a regular shot here is fine. Give it two switches and a really low delay, like 100ms. Since nobody actually hits the flipper buttons simultaneously anyway (there's always some slop), that should work.

**Comment by toomanybrians** [comment]
use a logic block with a timeout
