### ISSUE TITLE
Add switch times and inactive switches to shots

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#518]
Currently all the shot logic is based on a switch going active. We should add support for switches going inactive (or maybe going active then inactive), and also for timed switches (active for 500ms).

This could be built with some kind of micro language? (Or is this too much?)

Like:

```
shots:
  my_shot:
    switches: switch1|inactive, switch2, switch3|400ms, switch4|inactive|250ms
```

**Comment by jabdoa2** [comment]
Maybe we can also add dynamic pauses then: switch1,  300ms < wait < 2000ms, switch2|300ms|active or something. i like the idea of "switch3|400ms|active" as a general syntax. however, we should warn user that this event will be delayed by XXms and the time limit for the shot has to be longer therefore

**Comment by toomanybrians** [comment]
will be fixed via timed switch events
