### ISSUE TITLE
observable or subscriptable player vars?

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#523]
This is just a placeholder because I want to make sure we address this in some way at some point.

It would be nice to be able to set limits for player vars, so they can never exceed their bounds. That way a shot that adds 2500 points to some multiplier but a max of 10k could be handled at the player var level and not have to be implemented or configured at all the various logic elements scattered around.

Also it would be nice to be able to emit named events when player vars hit certain values, like

```
player_vars:
  intensity:
    0: low
    3: med
    10: high
```

This would post "high" when `self.player.intensity == 10`. This can be used for triggering slides on timers, on logic block progress, and lots and lots of other things throughout the game.

**Comment by jabdoa2** [comment]
I moved part 1 into #572. I think, the second part is solved. You can add an event handler on "player_intensity{value==10}". Is that sufficient @toomanybrians ?

**Comment by toomanybrians** [comment]
agreed
