### ISSUE TITLE
Game doesn't finish booting when shows are only in config

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#525]
(In 0.31) If shows are defined only in a config file, and there is nothing in the shows folder, the assets boot hold is never cleared. If you have any show in the shows folder, even if it's not referenced, everything works. If you have no shows folder, and you comment out the shows in the config, everything works.

The workaround for now is to just keep my dummy show in the shows folder.

**Comment by jabdoa2** [comment]
Can confirm that. Same happens when you only have shows or assets in a mode
