### ISSUE TITLE
Respect "count" confirm eject to playfield so no pf switches are needed

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#53]
If a plunger (for example), is set to confirm based on count, then it shouldn't matter whether pf switches are hit. The eject should be confirmed when the count expires, period. (And that should add to the pf ball count.)

https://missionpinball.com/forum/topic/problem-with-confirm_eject_type-count/

**Comment by jabdoa2** [comment]
Fixed in MPF 0.21
