### ISSUE TITLE
MPF was busy and a timed pulse did not run for it's entire time

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#532]
Not sure how to handle this. Scenario is a trough with a 1s timed eject. Worked fine through the first game. Starting the second game, the coil only fired for maybe 250ms instead of 1s. Could this be something where MPF was so busy that the command to enable the trough eject coil got delayed, but the disable command fired on time, so the result is that the coil was only actually active for less than 1 sec?

**Comment by jabdoa2** [comment]
Maybe because of the fast serial queue delay? Any warnings around serial in the log?
