### ISSUE TITLE
Add generic multiball start / multiball stop events

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#533]
Currently there are start/stop events for individual multiballs. However many pinball machines have rules that should apply when _any_ multiball is active. The problem with the individual multiball events if if you get stacked multiballs and you enable other modes or shots with start/stop events from these multiballs, one multiball ending will end that mode or disable that shot.

So we should create generic events like multiball_play_start and single_ball_play_start which can be used to start/stop things that should apply when any multiball mode is active.

Can we implement this as a class-level method with a flag, and each multiball start calls it and the event is only posted if the flag is not active, and vice versa?

**Comment by jabdoa2** [comment]
I would prefer a manager/controller class for this. Statics/class level variables cause problems in tests and are considered bad style.

**Comment by toomanybrians** [comment]
just use balls_in_play conditional events
