### ISSUE TITLE
sync_ms doesn't appear to work

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#538]
This will require some investigation, as there are tests for it, so maybe the tests are bad.

My experience with sync_ms is that it seems to have no effect. But that could be more related to how the shows do timing of their steps.

First, each step does everything it has to do, then it calculates how much time should pass until the next step starts and schedules the step. But if that step's actions time some time to run, it will still calculate the full duration for the next step. So this can cause drift over time (which is clear if you're running a bunch of shows at once that should be in sync.

Instead each step should be calculated from the beginning of the show (probably in delta time from beginning versus duration).

**Comment by jabdoa2** [comment]
The code does exactly that. It calculates all times relative to the start of the show (I changed that a few month back):

```
            self.next_step_time += time_to_next_step
            self._delay_handler = self.machine.clock.schedule_once(self._run_next_step,
                                                                   self.next_step_time - self.machine.clock.get_time())
```

**Comment by toomanybrians** [comment]
Turns out it's not an issue. Some LEDs with fades and some without made it look like they weren't in sync.
