### ISSUE TITLE
Debug logging overhaul

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#539]
Debug logging is almost worthless. Too much of some stuff. Not enough of others.

Maybe we make it so that the -v flag does nothing on it's own, but then only actually logs the verbose output of the areas that have debug: true?

**Comment by qcapen** [comment]
I totally agree.  A full verbose log is too cumbersome to work with when trying to debug a specific issue, not to mention too large to post and manage in a lot of editors.

**Comment by jabdoa2** [comment]
Thats very true. What about this:
no flags: just info (like currently)
-v: only debug where debug is true
-V: all debug

I think it would be probably best to implement this using logger filters. Then the devices would have to add themself to the whitelist.

**Comment by toomanybrians** [comment]
we can stack params too, so -v and -vv

**Comment by toomanybrians** [comment]
no -v, warning/error only, only show info for startup, bcp connection, etc.
-v, info plus debug only
-vv show everything  (also you are crazy, it will be 10mbps)

**Comment by toomanybrians** [comment]
this is done.
