### ISSUE TITLE
Allow conditional event handlers with URL param style events

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#548]
I want to add a feature where kwargs for event post handler calls can be pulled from the event name. And also handlers can register for certain combinations of kwargs and only be called if they match.

Example:

`self.machine.events.add_handler(my_event?foo=2)`

This handler will only be called if my_event is posted with foo=2.

`self.machine.events.post(my_event?foo=2)`

Will post the event my_event with the kwarg foo=2.

What's nice about this is it's a non-breaking change to existing configs.

For example in VC, we have one shot that kicks off modes when it's hit 3, 6, 12, 20, times etc. Of course we can do that with nested logic blocks (we actually use mode code since it's simpler), it would be cool to have an event player like:

```
event_player:
  player_my_var?value=3: start_mode_1
  player_my_var?value=6: start_mode_2
  player_my_var?value=12: start_mode_3
```

Eventually we could probably have ranges or regex or something, but for now even exact matches would be great and easy to implement.

I think we implement this at the EventManager level, so if a handler is registered for an event with a question mark and equals sign, we do this conditional registration.

This would be helpful for VC, so I'd like to do it for 0.32. I think it should be a pretty easy implementation.

**Comment by jabdoa2** [comment]
Also want that feature. Would also work with sympy and booleans which would make it much more powerful

**Comment by jabdoa2** [comment]
My approach here would be event{sympy_expression}. I would use {} because normal brackets are quite usual in boolean expressions. I propose that we also expose all settings and player vars here. So you can do something like this:

ball_started{settings.bonus_on_last_ball and ball == 3}

Or: 
ball_drain{settings.extra_ball_for_10_loops and vars.loops >= 10}

**Comment by toomanybrians** [comment]
Awesome. Love the idea of getting settings and player vars and other limited attributes in there! Would be cool to support Python slice notion as well for accessing attributes.

Man, this is becoming a real DSL!!

**Comment by jabdoa2** [comment]
This works now: 
`self.machine.events.add_handler("test{settings.test == True}", self._my_handler1)`

or:

`self.machine.events.add_handler("test{settings.brightness > 90 and (param1 == 7 or param2 > 20}", self._my_handler2)`

We can add everything what python supports. Currently, thats still a bit limited.
