### ISSUE TITLE
Ball Lock and balls_in_play

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#560]
Currently, when we lock a ball in the ball_lock we do not change balls_in_play.Tthis is independent of "request_new_balls_to_pf". Therefore the issue: Should balls in the lock be included in the "balls_in_play" count?

If yes: You cannot loose the game when one ball is locked.
If no: with "request_new_balls_to_pf" set to False", the game would end once you lock the last ball on pf.

**Comment by jabdoa2** [comment]
Decision: move  "request_new_balls_to_pf" to Multiball device

**Comment by jabdoa2** [comment]
Implement distinct delay_ball_lock and multiball_ball_lock. Only the later would reduce balls_in_play and would count virtual balls.

**Comment by jabdoa2** [comment]
multiball_lock:
- keep count per player. real count does not matter
- keep balls in device only up to the maximum number over all players
- make sure there is either a replacement lock (like on dr who) or eject a ball on player change to make room

**Comment by toomanybrians** [comment]
I think we can do this for config version 4 / 0.33 because I'll add two new sections and keep the original ball_locks:, then we can deprecate the original ball locks in config version 5

**Comment by jabdoa2** [comment]
This is mostly fixed. We need to deprecate ball_locks
