### ISSUE TITLE
New device for sequential events?

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#564]
We need a way for multiple things in config files to register for the same event, but where each callback is called one-by-one, with the next one only being called after the previous one releases it. (This is almost like combing our "relay" and "queue" event types, but a bit different, as I'll explain.)

The use case is pretty common I think. (We're running into this in VC.)

Example: you have a shot with two things lit, like _extra ball_ and _start mode_. You hit that shot, and in the machine, you want the extra ball to be handled first, to play its award show and do whatever it has to do, and then once that's done, you want the mode to start.

This isn't quite like relay events, because relay events call the next handler immediately when the prior handler returns. And it's not quite like queue events, because queue events let a handler "pause" the handling of the original callback, but there's no concept of order or one callback notifying the next callback that a prior one is done.

I could see this as either a new event type, like "sequence_events" or something (or "sequential_queue", or ... ???)

Here's how I envision this being exposed to configs. First, we add a section called "sequence_events" (or whatever we call it), where we can take any event in MPF (these can be any standard event, not just queue or relay events), and we map them to the name of the event we want to use in the configs, like this:

```
sequence_events:
  center_kickout_ball_enter: center_shot
```

Then in configs, users could register for the relay events just like regular events.

```
# extra_ball_mode
show_player:
  center_shot: my_show
```

```
# start_mode_mode
show_player:
  center_shot: start_mode_show
```

etc.

Each place that uses this event would post something like `<event_name>_done` to indicate that it's done with its processing, and that would cause the event_relay player to then call the next registered handler. So in the above example, "center_shot" is not a real event that's ever posted by the normal event manager, rather the event relay handler just looks for registered handlers for that event and calls them one-by-one.

The handlers can be called in the order of the standard priorities (which would tie into the mode priorities and everything).

The other advantage of this is that it clears up how we handle the order of things that may or may not happen on mode end, ball end, ball start, game end, etc. And modes/handlers that are active will respond, and they can take as much time as they need, then the next one is called, etc.

Also this is cool because it converts any event type into this relay queue thing, rather than now it only works with certain events.

I feel like this is important functionality that I'd like to fast track for 0.32. Will be hugely helpful in VC.

**Comment by jabdoa2** [comment]
Proposal: Implement those like queue events but call the handler sequentially instead if all at once. Would serve the same purpose but probably more universal. We should probably make this the default queue event

**Comment by toomanybrians** [comment]
This seems ok to me. We could call it an asynchronous queue versus a synchronous queue or something. The only other thing to figure out is how we access clearing the queue item via config files. But that can be something that's handled in the queue_event_player: (a new entry which would translate normal events into queue events.)
