### ISSUE TITLE
Count bonus multiplier from 1

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#573]
Currently with the first scoring of a bonus we set the bonus to 1 but it should start at 1 and go to 2 after the first increase.

Depends on #572
Add test for bonus mode.

**Comment by jabdoa2** [comment]
@toomanybrians is it enough if we just document that you have to create a config like this:

```

player_vars:
    bonus_multiplier:
        initial_value: 1
```

**Comment by toomanybrians** [comment]
Works for me.
