### ISSUE TITLE
shot_profile: player_variable doesn't make sense when applied to more than one shot

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#593]
Currently we have a `player_variable:` setting in shot profiles that lets you override the name of the player var that will hold the current state of that profile. (The default player var is a combination of the shot name and profile name.)

The problem is that if you apply a profile with a custom var name to more than one shot, it breaks the shots since essentially you have multiple shots using the same var which means they can't have their own states. (Maybe that's a feature? Probably not.)

I vote that we just remove that setting. Reason is that to keep a single player var which is shared across shots, we'd have to store some kind of array or dict or something which is probably not desirable.

Alternately we could make it so that the player var setting was not valid if a profile is applied to a shot group (but valid if it's applied to a single shot), though that sort of seems like a band-aid to cover bad design.

**Comment by jabdoa2** [comment]
removed
