### ISSUE TITLE
Modify event_player to not pass args to new events

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#599]
Trying to fix https://github.com/missionpinball/mpf/issues/598, I tried to put my event with args through the event_player in order to generate a normal event without the args, like this:

```
event_player:
  player_world_tour_world_tour_timer_tick{value == 5}:
    slow_down_timer
```

Putting slow_down_timer into the control event (the one in the bug I liked to) performs the same as it would if it was the event with an arg. This means that event_player passes the args from the "source" event to the "new" event.

I modified the `play` method in event_player.py as follows (just the last line):

```
    def play(self, settings, context, priority=0, **kwargs):
        """Post (delayed) events."""
        for event, s in settings.items():
            s = deepcopy(s)
            s.update(kwargs)
            if '|' in event:
                event, delay = event.split("|")
                delay = Util.string_to_ms(delay)
                self.delay.add(callback=self._post_event, ms=delay,
                               event=event, s=s)
            elif ':' in event:
                event, delay = event.split(":")
                delay = Util.string_to_ms(delay)
                self.delay.add(callback=self._post_event, ms=delay,
                               event=event, s=s)
            else:
                self.machine.events.post(event) #, **s)  ### This is the modification
```

This prevented the args from passing between events, and it fixed my problem.

The question is, should event_player pass args? And, if there are situations where it should, can we make it a user-configurable option to turn that off? If so, how do we implement that?

**Comment by toomanybrians** [comment]
don't pass by default, make setting for yes

**Comment by jabdoa2** [comment]
@GabeKnuth is this still an issue?

**Comment by GabeKnuth** [comment]
This was my workaround to https://github.com/missionpinball/mpf/issues/598, and while working around it I discovered this behavior. I am still using that workaround in BnD, and it didn't cause any problems.

I think I just wanted to start the discussion about whether or not event_player should pass args all the time, or if it should be configurable. In general, I think it would be good to have that flexbility, but I don't have a need for that feature right now.

**Comment by jabdoa2** [comment]
@GabeKnuth I guess this can be closed since I fixed the underlaying issue, right? reopen if you need it please!
