### ISSUE TITLE
Add timeouts to logic blocks

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#608]
Add a timeout to logic blocks such as counters, sequences and sequels. It should reset the block if it expires. This should only cover this very basic usecase and everything advanced can use an external timer.

**Comment by atummons** [comment]
Jan,  I'll take this one.  I have it 90% done, but not sure how to instantiate a timer.  I have looked at code elsewhere, but its completely different between high scores and sequence shots.  How should this be implemented?  When it is enabled, I want to start the timer (in its own def), and when it hits the value set in the config, then it should trigger.  The def calls the reset method, and restarts the timer (reset calls the def to reinstantiate it).

I am sure there is some module that already exists that says when the method is called start ticking.  Then I can write my def to write a while loop and check the timer against the value in the config.  Then when its called again, it would reset that system timer and go again.  Any method or imported class would help so I am not trying to reinvent the wheel.  Once that is done, I have the tests written, and should be just some minor debugging.

**Comment by jabdoa2** [comment]
Awesome. We usually use `DelayManager` for that. If you search the MPF code you should find a few examples. If not please ask.

Jan

**Comment by atummons** [comment]
Jan,

Thanks! After going around a bit more I found the delays.py, etc high contains that. I was just struggling with how to pass the arguements. But now that I have this, I think I should be able to get it working.

I am doing one at the logic block level called logic_lock_timeout that works for all three (counters, accruals and sequences). Are you okay with that? Or do you want me to build it at the lower level and have counter_timeout, etc.?

**Comment by atummons** [comment]
Jan,

Handled in PR 1564.  We can move convo over there, and then close this once we get that approved and merged.
