### ISSUE TITLE
config validate P-ROC switches to ensure direct 0-7 are not used with rows 8-15

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#668]
Since the P-ROC doubles direct switches 0-7 as row 8-15 returns, we should add something to the P-ROC validation to ensure that there are no SD0 - SD7 switch numbers if any switches have row numbers 8-15. Currently the P-ROC will silently pick one if there's a conflict (I don't even know which one) and it's confusing since the user probably doesn't know they have the conflict.

**Comment by jabdoa2** [comment]
What exactly do we need to check? How would row 8-15 switches look?

**Comment by jabdoa2** [comment]
Once SD0:7 is used any x/y with y>7 should throw an error
