### ISSUE TITLE
Python 3.6 Support for Mac

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#734]
Travis for MacOsX fails: "AssertionError: Incorrect Python version. MPF requires Python 3.4 or 3.5. You have Python 3.6.0."

**Comment by toomanybrians** [comment]
change travis script to force python 3.5 for mac (since 3.5 is what's in mpf.app)

**Comment by jabdoa2** [comment]
Python 3.6 works. You can give it a try on Mac if you want.

**Comment by jabdoa2** [comment]
should work so far
