### ISSUE TITLE
"Displays:" default setting can cause issues

### ISSUE THREAD

**Issue by cfbenn** [missionpinball/mpf#750]
If leaving out the Display option, MPF falls back on some strange default that can cause weird and unexplained behaviour.

Attached is a sample config and details (rename .txt to .zip)

[MPF Bugs.zip.txt](https://github.com/missionpinball/mpf/files/709275/MPF.Bugs.zip.txt)

**Comment by jabdoa2** [comment]
https://github.com/missionpinball/mpf-mc/issues/230

**Comment by toomanybrians** [comment]
closing this since we have an issue for it in the mpf-mc repo
