### ISSUE TITLE
Add monitorable attributes to conditional events

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#758]
We should expose the attributes that are exposed to the monitor to conditional events. I think devices are probably uniquely named so maybe we can do it with just the name.attribute?

Example here: https://groups.google.com/forum/#!topic/mpf-users/4vb5NaJAO8A

**Comment by jabdoa2** [comment]
Reason why I did not implement this yet is that this would make this a public API which should be somehow stable. We should invest some thoughts about how we design this to be relatively stable in the future to not break user code too often.

**Comment by jabdoa2** [comment]
Shortly investigated this. Main issue seems to be that MPF-MC would have to subscribe to all devices (like the monitor) which would consume a lot of resources because we will also send all LED and lights updates. This is ok for the monitor because it is a debug tool but looks like a lot of overhead for MC to me.

**Comment by toomanybrians** [comment]
I'm going from memory here, so this might not exactly be right.. But for plugin players that send stuff to the MC, I think the way they work in a show is different than how they work with a standalone config entry. In a show, there's a BCP trigger which is something like "play_slide" or "play_widget", whereas the standalone players actually register (and later deregister) the events and just handle everything locally in the MC.

So we could change it so that all plugin players use that play_xxx triggers (with a json dict of the settings?) and that way the MC side could be all trigger based and wouldn't have to use the event manager at all?

We'd have to figure out how things like animations worked that were triggered from events, but again the plugin on the MPF side could handle that and send the triggers with json configs which the MC would just do.

Hopefully that could lead to getting rid of the event manager on the MC side long term? And maybe even the MC wouldn't need to know about modes and all that? (keys and clears and all that could come from the MPF side.)
