### ISSUE TITLE
New design for shots in config_version=5

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#767]
Shots need to be redesigned. Here's a structure for the ideas:

1. The basic concept of shots and how they’re defined does not change
  
2. Change the *shot_(name)_hit* event so it’s one of the queue relay events. So that will solve the issue where you have two inserts lit for a single shot (maybe extra ball and mode start) and you want to service the extra ball first, then pass to the mode

3. Shot profiles are gone
 
4. Dealing with lights is done with shows. If you want a higher mode to turn off a light it doesn’t use, you can use a show with the color black

5. There can be some kind of “block” function if you want to block a shot event from going to a lower mode. Maybe we can do that today with the queue relay event and returning false or something? If not we can add that at the queue relay level, not shots.

Alternately you could just redefine the shot if you need it differently in your mode. then unload the lower mode if that functionality should be gone. Dunno if that is always feasible but that is how it works in a lot of cases currently
 
6. Shot groups that rotate (like with lane change) can be some kind of special case, like in a “shot_rotators:” section or something. Currently shot profiles are used a lot to enable rotation yet rotation probably is only a thing on 5% of shots. The shot rotator can get a list of shots defined as well as their lights, and it can handle transferring shows (using tokens) from light to light as rotation happens.

7. Managing shot state can be done with a logic block. Possibly this could be done with existing logic blocks, or maybe a new type is needed. Or maybe some kind of new link is created to make this easier that uses logic block functionality under the hood.

8. Shot groups are removed. But we need something to check the state of multiple shots and post events when they're all complete. Maybe that's like 7 above where it's done with a logic block (existing or new?), and maybe it's integrated in some way? So actually maybe shot_groups: still exists (just to check group state, not to rotate). Have to figure out for sure...

**Comment by jabdoa2** [comment]
shots simplified. should be maintainable now.
