### ISSUE TITLE
ball search should ignore switch hits from active devices

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#779]
In BnD, we're finding that when the coils from some autofire coils devices are pulsed on ball search, their associated switches are activated. This has the effect of canceling the ball search even though it didn't find a ball.

I'm thinking the easiest way to do this is to add a new method to the switch controller to temporarily ignore a switch. So it can be like:

`self.machine.switch_controller.ignore_switch(name, ms)`

Then we'll maintain a list of ignored switches. This could potentially be used with broken switches in the future. In the case that the ignore_switch() includes a ms setting, we'll just set a delay to remove it.

Probably this should only affect whether the switch events are posted and the callbacks are called so that it doesn't break the actual state of the switch.

With ball search, we can just have the devices call the ignore switch method with the ms that they will be active for plus some percentage (10% or something like that)

**Comment by jabdoa2** [comment]
@toomanybrians fixed?

**Comment by toomanybrians** [comment]
not yet. I need to make a similar fix like you did for drop targets to autofire coils too.

**Comment by jabdoa2** [comment]
Tracking progress in #787
