### ISSUE TITLE
Suggest adding config option for num tries before increasing pulse in ball_device

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#806]
Currently we have the ability to increase pulse time after failed ejects from a ball_device, but the number of retries before we increase the pulse time is hardcoded to 4. That can take a long time, and could be critical in situations like the drain>trough mechanism on a System 11-style trough. For example, in BnD, if one eject from the drain fails, I want it to increase the pulse because there might be two or even three balls waiting. If I have to wait for three retries before it increases pulse, A) ball search will turn on, and B) odds are I don't have enough power to move three balls. 

So, I suggest adding a setting to ball_device configs similar to "retries_before_increasing_pulse" and using that number instead of the hardcoded "4" below.

```
class PulseCoilEjector(BallDeviceEjector):

    """Pulse a coil to eject one ball."""

    def eject_one_ball(self, is_jammed, eject_try):
        """Pulse eject coil."""
        if (eject_try <= 2 and
                self.ball_device.config['eject_coil_jam_pulse'] and
                is_jammed):
            self.ball_device.config['eject_coil'].pulse(
                self.ball_device.config['eject_coil_jam_pulse'])

        elif eject_try >= 4 and self.ball_device.config['eject_coil_retry_pulse']:
            self.ball_device.config['eject_coil'].pulse(self.ball_device.config['eject_coil_retry_pulse'])

        else:
            self.ball_device.config['eject_coil'].pulse()

        self.ball_device.debug_log("Firing eject coil. Current balls: %s.",
                                   self.ball_device.balls)
```
Attached is a log file of what happens where there are bunch of balls waiting in and around the drain. This game powered on with balls waiting down there and immediately went into ball search. I fixed that manually, then started a 4-ball multiball and tried again. Lots of ball searching and eventually there were three balls in the drain that weren't going anywhere.

[multiball test - MPF.log.zip](https://github.com/missionpinball/mpf/files/821931/multiball.test.-.MPF.log.zip)

**Comment by jabdoa2** [comment]
Sure makes sense
