### ISSUE TITLE
MPF Fonts not using "baseline"

### ISSUE THREAD

**Issue by 3dmation** [missionpinball/mpf#807]
This is a fairly easy thing to show.  I'll suggest using the Service Menu code as an example.  Inside you can scroll through to "Switch Test", "Coil Test" or "Settings".  The "Settings" text the "g" is an overhanging character.  The position however, should not change on a font that uses it, since where the anchor point or default position stays the same from it's "baseline" as it's traditionally called in the font world.  In MPF though, it looks like it's using the center of the extents created.  This is not the same thing, as an overhanging character can cause this center to be higher and lower depending on what text is in the box.

I'm not sure the solution.  I'd imagine each font has it's baseline somewhere defined in it, so MPF must somehow find it and use it.

**Comment by toomanybrians** [comment]
moving this to mpf-mc issues https://github.com/missionpinball/mpf-mc/issues/244

**Comment by toomanybrians** [comment]
This has been fixed.
