### ISSUE TITLE
Add brightness option when specifying LED color

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#812]
Currently there’s no brightness adjustment for LEDs. I’d like to be able to set an LED’s brightness to 50% of its specified color. If I just used FFFFFF for the color of all LEDs, that’s no problem because I can just use 808080 as the 50% color. However, on BnD I have a mix of colors. Some are tuned to the color of the insert, while others are set to a “warm white” color of ff9027. 

50% of ff9027 is 7f4813, but rather than calculating the various percentage values for each LED, it would be great if we could find a way to specify the brightness when we specify the color in a show or led_player or whatever. 

Talking to Brian, it sounds like we already do fade times for colors in config, like “red-f20”, so perhaps we can add “-bxx” for brightness. The config would read something like “l_begin_round: on-b50” to get that light to turn on at 50% brightness of the color specified in the leds: section of the machine config.

**Comment by jabdoa2** [comment]
This would have to go into color parsing in RGBColor. Maybe red%50? We need to find an intuitive format.

**Comment by GabeKnuth** [comment]
The only problem is if we also use -fxx, we'll have a color string like `red%50-fxx`, which isn't as intuitive as one that has "fields" separated by dashes. `red-b50-f200` seems intuitive and leaves us the ability to add something else later that follows the same scheme.

**Comment by jabdoa2** [comment]
Dunno. Those could not be mixed anyway. Because fade happens in the player but the brightness modifier can be used everywhere. So brightness have to come first

**Comment by qcapen** [comment]
If you are looking to always have a particular light use a fixed brightness, you can do that today with color compensation.  Just set the maximum output level to 50% when creating the color compensation profile.  Colors often do not look quite right when "divided in half" as we are dealing with 8-bit channel precision in what effectively becomes a 7-bit number so some additional fine tuning is often needed.

**Comment by jabdoa2** [comment]
We needed 16bit color resolution for platforms ;-)

**Comment by jabdoa2** [comment]
Did a quick implementation here: https://github.com/missionpinball/mpf/pull/817/files#diff-99fbdc001b7245962e7f7c1ac64479deR61
