### ISSUE TITLE
Random event player "plays" event a bunch of times

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#826]
I'm reasonably sure this isn't a config problem, but I could be wrong. 

In BnD, I have a show (mc_intro_show) in a mode (managers_choice) that plays an event: mc_choose_award.

That event triggers a random_event_player in the base mode that chooses from a list of events. For some (not sure if it's all) of the chosen events, the event is posted many times, almost exactly 500ms apart. This is reproducible, at least with the mc_10_points event and the mc_start_ball_saver events.

I think this is an MPF thing because mc_choose_award is only posted one time.

Game code is here: https://github.com/gabeknuth/bnd

Logs attached. Event that posts too much is mc_10_points.

[Archive 9.zip](https://github.com/missionpinball/mpf/files/860348/Archive.9.zip)

**Comment by toomanybrians** [comment]
What's the keystroke sequence to reproduce this?

**Comment by GabeKnuth** [comment]
S L 7 8

**Comment by GabeKnuth** [comment]
I might have found the problem in a show. Will test later.

**Comment by GabeKnuth** [comment]
Yep. The same event posted by the random event player was also posted in a show kicked off by the event played in the random event player. I don't know why they kept posting over and over, but I'm happy with it just working for the moment.
