### ISSUE TITLE
Use modulus operators in conditional events?

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#832]
Trying to use event player to post an event every 8th time a conditional event is posted. Specifically, every time the hit_jukebox event from a counter logic block posts with a value divisible by 8, I want it to post the same event. 

So, I tried to do this:
```
event_player:
  hit_jukebox{count%8==0}:
    start_light_lock
```
but it crashes my game.

There are other ways around this, but this seemed like the simplest (i.e. fewest lines of code/config) to me. 

Log attached. No rush. I can do what I need to do in mode code. 
[crash using modulus in conditional event.zip](https://github.com/missionpinball/mpf/files/869673/crash.using.modulus.in.conditional.event.zip)

**Comment by jabdoa2** [comment]
I will add that. Currently simply unsupported
