### ISSUE TITLE
Game start/stop procedure

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#838]
Make sure this always holds true:

- Game start
- self.machine.game is set
- Other modes start
- Game stopping (via .stop() or event or last ball drained)
- Game state stopping
- Bonus modes and others run
- All game modes stop completely (including unregistering devices and config_players)
- Game stops
- self.machine.game is unset

Currently, we fail to unload all modes including their devices before game stops in some cases (e.g. when calling stop on the self.machine.game). Service mode can trigger crashes this way

**Comment by GabeKnuth** [comment]
Will this allow us to add the ability to do the long press on the start button to end the current game and start a new one?

**Comment by jabdoa2** [comment]
Probably yes
