### ISSUE TITLE
Kickback doesn't post "fired" event

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#850]
On Mike Wiz's machine, his kickback device doesn't post the kickback_(name)_fired event when it kicks the ball back. He's on .32, so I'll investigate more. Just want to track the issue here. We'll upgrade him to dev tomorrow and see if that works. dev code seems like it should work fine to post the event in the _hit method.

**Comment by jabdoa2** [comment]
Did you test this? Does not quite sound like that here: https://groups.google.com/forum/#!topic/mpf-users/TRz4dwTVtbk. Otherwise, there would be no sound.

**Comment by GabeKnuth** [comment]
I tested this myself. When the kickback fires, that event does not post. We
changed his sound player to to fire on the switch event and the sound
plays. We're using a slightly different config than what was posted in the
Google group.

I will dig some more today. I only posted that issue so I didn't forget to
dig a little deeper. The code is super simple, and it looks like that event
should post, so I imagine something is strange on our end.

**Comment by jabdoa2** [comment]
Any update on this?

**Comment by jabdoa2** [comment]
@GabeKnuth Any news on this? Otherwise I would just close it.

**Comment by jabdoa2** [comment]
closing this for now since it is very old and probably resolved. feel free to reopen otherwise
