### ISSUE TITLE
Command-line config generators

### ISSUE THREAD

**Issue by unRARed** [missionpinball/mpf#924]
Maybe something like this already exists that I'm not aware of, but it would be cool to have a Rails-like command-line interface for generating a machine config which may or might not have some suggested conventions as to filenames and directory structure:

A couple examples that come to mind:

* `mpf config init` - kicks off a series of questions and establishes dev/prod environments and initial hardware config based on the answers to those questions.
* `mpf config create mode ModeName` - creates the `modes/mode_name/*` directory structure as well as `tests/test_mode_name.py` (to encourage testing our configs).

Of course, there's probably infinitely more neat things that could be be done with this. It came to my mind after copy/pasting the testing of a game config from one of the examples.

**Comment by jabdoa2** [comment]
Good idea. Do you want to work on that?

**Comment by unRARed** [comment]
Yea, potentially beginning in mid-June anyway. I have my hands full at the moment trying to get our machine into a playable state for the PNW Pinball Expo which is June 9th. Do you think it would be better to use the existing `mpf` cli or a new separate one (i.e. `mpf-generate`, `mpf-make`)?

**Comment by jabdoa2** [comment]
Cool. mpf config sounds good to me. Let us know when you need any help.

**Comment by unRARed** [comment]
Will do. And just for clarity, `mpf config` (new arg) or `mpf-config` (new command)?

**Comment by jabdoa2** [comment]
Mpf config is actually a command in mpf. Like mpf game or mpf mc.

**Comment by unRARed** [comment]
haha, probably good to know this then =)

**Comment by toomanybrians** [comment]
I like this a lot. It would be cool to include some options that pop up for some of them.. like asking if the user wants custom mode code for the mode option.

Sphinx has a `sphinx-quickstart` command that asks some questions and then builds a `conf.py` config file from it. I have no idea how it works or if there's any value here, but it might be worth looking at? https://github.com/sphinx-doc/sphinx/blob/bf3f9ef3ecc94067a2f9b17f2c863e723cf3e7af/sphinx/quickstart.py

Also really love the auto creation of the test modules too! :)

**Comment by jabdoa2** [comment]
@unRARed do you still want to work on this?

**Comment by unRARed** [comment]
I've been consumed by other projects lately, so I can't see myself getting to this is the near-term. I do think it would be a helpful feature to bootstrap a project.

**Comment by F4b1-** [comment]
I like the idea as well and since the issue has been idle for quite some time I would like to start working on it.  I was thinking about using the [prompt_toolkit ](https://github.com/jonathanslenders/python-prompt-toolkit) library for the  command line interactions. I would just call the command create-config (_mpf create-config_ would start the series of questions).  I would try follow the tutorial for a simple game to find the kinds of questions that should be asked.

**Comment by jabdoa2** [comment]
Go for it! The toolkit looks cool. I created an initial commands a while ago: https://github.com/missionpinball/mpf/blob/dev/mpf/commands/scaffold.py. Feel free to modify that. Or create a new command. What every you want.
