### ISSUE TITLE
Make sure there is only one device with tag ball_add_live

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#930]
More than one device with that tag will lead to undefined behavior.

Add a "source_device" to the playfield which is used to request balls.

**Comment by toomanybrians** [comment]
I wonder if we should add a setting to the playfield device which is the name of the tag that's used to add a ball to that playfield? Then we make sure that there is only one device with that tag? (And we make the default setting ball_add_live.)

That way for games with multiple playfields, each can have its own ball add live tag and this logic will still work

**Comment by toomanybrians** [comment]
Though... now that I write that, I guess per playfield is kind of a different thing, since this tag is used to increase the live ball count, which is different than just adding a ball to a pf?

**Comment by jabdoa2** [comment]
Yeah makes sense. I like it.

**Comment by jabdoa2** [comment]
Plan is to deprecate ball_add_live for 0.50. Is was only used to select the device. Increasing ball count etc is done independently. So @toomanybrians first idea of making this a setting in the playfield totally makes sense. Only downside would be that everybody has to define the default playfield object.
