### ISSUE TITLE
Add Windows Python 3.5 and 3.6 support to P-ROC pinproc wheels

### ISSUE THREAD

**Issue by qcapen** [missionpinball/mpf#935]

**Comment by qcapen** [comment]
Would like to automate the Windows wheel building process with Appveyor, rather than using Visual Studio on my personal PC.

**Comment by qcapen** [comment]
**pypinproc & libpinproc manual Windows build instructions for Visual Studio 2010**

Setup the environment

	1. Ensure you have Visual Studio 2010 installed with C++ and 64-bit support
	2. Download and install cmake (http://www.cmake.org) and add <your-cmake-directory>\bin to your path.
	3. Install Python 3.4.  Be sure the main Python directory and the /Scripts sub-directory are added to the Windows PATH
	4. Create a directory to hold all build project components (ex: D:\p-roc)
	5. Download and extract libpinproc from GitHub (https://github.com/preble/libpinproc) into the directory you created in the previous step.  Be sure to rename the directory to libpinproc (remove any GitHub branch suffix)
	6. Download and extract the MPF version of pypinproc from GitHub (https://github.com/missionpinball/pypinproc/tree/dev) into the directory you created to hold all project components (ex: D:\p-roc\pypinproc).  Be sure to rename the directory to pypinproc (remove any GitHub branch suffix).
	7. Download and extract the ftd2xx USB driver for Windows (http://www.ftdichip.com/Drivers/D2XX.htm). These instructions were tested with version 2.12.10.  Put the extracted ftdi folder into the libpinproc folder you made above (ex: D:\p-roc\liblinproc\ftdi)
	8. Download and extract yaml-cpp (https://github.com/jbeder/yaml-cpp) into the libpinproc directory you made above (ex: D:\p-roc\libpinproc\yaml-cpp). Important: use version 0.3.0 as the new version 0.5.0 does not work yet since the API.


Build yaml-cpp

	1. From the Windows command line, 'cd' into your yaml-cpp directory and run the following command: cmake -G "Visual Studio 10 2010 Win64" -DBUILD_SHARED_LIBS:BOOL=OFF
	2. Note: the above command will not work if cmake is not in your PATH environmental variable
	3. Now run Visual Studio 2010 and open the YAML_CPP.sln file created by cmake. Build the solution in Debug and Release.


Build libpinproc

	1. From the command line, 'cd' into your libpinproc directory and run the following command: cmake -G "Visual Studio 10 2010 Win64" -DEXTRA_INC=".\ftdi;.\yaml-cpp\include" -DEXTRA_LINK=".\ftdi\amd64;.\yaml-cpp\Release;.\yaml-cpp\Debug"
	2. Now run Visual Studio 2010 and open the PINPROC.sln file created by cmake. You can build both Debug and Release solutions.


Build pypinproc

	1. NOTE: There is no cmake support for pypinproc and I was not successful in using Python setuptools to build the pypinproc extension.  I was successful in setting up a brand new Visual Studio 2010 project to build the pypinproc extension library for Python 3.4.
	2. Create a new Visual Studio 2010 project (Visual C++ Empty Project template).  Use pypinproc for the project name and use the main directory created during setup as the project location (ex: D:\p-roc)
	3. Add the existing pypinproc files to the project (select pypinproc.cpp, py3c.h, dmdutil.cpp, dmdutil.h, dmd.c, and dmd.h).  Repeat the process for all the header files in the py3c sub-directory.
	4. Modify the project properties:

		1. Set the following options on the General section: Target Name=pinproc, Target Extension=.pyd, Configuration Type=Dynamic Library (.dll)
		2. In the VC++ Directories section, add the following Include Directories: ..\libpinproc\include, PYTHON INCLUDE DIRECTORY (ex: C:\Python34\include)
		3. In the VC++ Directories section, add the following Library  Directories: ..\libpinproc\Release, ..\libpinproc\ftdi\amd64, PYTHON LIBS DIRECTORY (ex: C:\Python34\libs)
		4. In the C/C++ Preprocessor section, add the following Preprocessor Definitions: WIN32;_WINDOWS;NDEBUG;
		5. In the Linker Input section, add the following Additional Dependencies: python34.lib, libpinprocmd.lib, ftd2xx64.lib

	5. There are a few incompatibilities in the pypinproc C code with the Visual Studio 2010 compiler that require some modifications to the source:

		1. In dmd.h, replace "inline" with "__inline"
		2. In dmd.c, all variable declarations must be done at the very beginning of each scope level.  The code must be rearranged to meet this old C 89 requirement since VS 2010 does not support the newer C standard.

	6. Build the extension library.  pinproc.pyd will be in the Release directory

**Comment by jabdoa2** [comment]
@qcapen you fixed this in 0.50, right?

**Comment by qcapen** [comment]
Yes
