### ISSUE TITLE
Remove number format hex

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#968]
Caused too much confusion for users.

Default to int format and remove hex from config_spec

**Comment by gabriellim** [comment]
Is this just changing line 464 of config_spec.py from
```config_number_format: single|str|hex```
to
```config_number_format: single|str|int```

**Comment by jabdoa2** [comment]
Essentially yes. Probably adjusting a test or two and updating the documentation.

**Comment by gabriellim** [comment]
Ok cool thanks, I'm just trying to figure out how to submit a pull

**Comment by jabdoa2** [comment]
Looked into it some more. In a second step, we could remove the complete line in config_spec (to remove the setting) and just use int as default branch here https://github.com/missionpinball/mpf/blob/dev/mpf/platforms/fast/fast.py#L286.

**Comment by jabdoa2** [comment]
@gabriellim how are you? can i help you with anything?
