### ISSUE TITLE
Ball search failed action: end_ball

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#972]
Implement `end_ball` as ball_search_failed_action in ball_search. It should just end the ball and not the game as `end_game`.

**Comment by ashanhol** [comment]
Hi @jabdoa2! I was looking through ball_search, were you thinking of another if statement in  _compensate_lost_balls()?

**Comment by jabdoa2** [comment]
Yes,  that would be the right place to implement this. Thanks for looking at this!

**Comment by jabdoa2** [comment]
This was a feature request from one of our users: https://groups.google.com/forum/m/#!topic/mpf-users/F60DMIKll_g

**Comment by ashanhol** [comment]
While this seems to be a quick fix #992, I found that the unit tests written for [ball_search](https://github.com/missionpinball/mpf/blob/dev/mpf/tests/test_BallSearch.py) seem a bit complicated. I'm not sure how to go about adding one. 

On a separate note, I think it might be a good idea to add additional links to the contributing page http://docs.missionpinball.org/en/latest/about/contributing_to_mpf.html as it doesn't list that this project requires python v 3.4 there.

**Comment by jabdoa2** [comment]
thanks for implementing this @ashanhol
