### ISSUE TITLE
Annotate extra ball events

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#990]
Currently events in mpf/devices/extra_ball are not annotated. Though, they are missing in the docs.

**Comment by RoseAndres** [comment]
Is there any documentation for annotation standards for the mpf?

**Comment by jabdoa2** [comment]
Good point. We need to document that as well probably. The goal of this issue is to add docblock comments such as this one: https://github.com/missionpinball/mpf/blob/dev/mpf/devices/ball_save.py#L162

  
  self.machine.events.post('ball_save_{}_grace_period'.format(self.name))
        '''event: ball_save_(name)_grace_period
        desc: The ball save called (name) has just entered its grace period
            time.
        '''

We parse those comments on readthedocs and show them like this: http://docs.missionpinball.org/en/latest/events/ball_save_name_grace_period.html

**Comment by RoseAndres** [comment]
Got it. I'll start working on it when I get back home tonight.

**Comment by RoseAndres** [comment]
Can I get some help merging my changes in? This is my first time contributing to a project on GitHub.

**Comment by jabdoa2** [comment]
Sure. How can I help? Your workflow should look like this :

1. Fork the MPF repository on github
2. Clone your fork (git clone https://github.com/... mpf) and change into directory (cd mpf) 
3. Checkout dev branch (git checkout dev) 
4. Create your own (local) branch (git checkout -b add_doc_blocks_in_extra_ball)
5. Make your changes
6. Review your changes (git diff) 
7. Commit all changes locally (git commit -a)
8. Push your branch to github (git push add_doc_blocks_in_extra_ball)
9. Go to github.com and click on Create Pull Request
10. Wait for review and merge from us

**Comment by RoseAndres** [comment]
That's perfect thanks! I'd left out a couple of those steps when trying to get my changes set up for a pull request yesterday. I'll finish it up tonight. 

Also, would the lack of documentation about the event annotations (or annotations in general) be worth opening up an issue for?

**Comment by jabdoa2** [comment]
I guess that documentation could go here: http://developer.missionpinball.org/en/dev/. If you want you can add it there (using the "edit on github" button) or just create a new issue. Developer documentation actually lives inside the mpf repository while docs.missionpinball.org lives in mpf-docs.

**Comment by RoseAndres** [comment]
I ended up having to use "git push --set-upstream origin remote" in order to get the branch to push. About to submit the pull request.
