### ISSUE TITLE
PEP8 Style Warnings

### ISSUE THREAD

**Issue by colin-mullikin** [missionpinball/mpf#993]
I came across your repo on YourFirstPR and, while looking around, noticed that you have quite a few (709) Style messages according to Landscape. I don't have a lot of Python experience, but I figure fixing these might be a good way to familiarize myself with the language and your code base.

Is this something that you guys are open to, @toomanybrians?

As there are so many and it could take quite a while, it might be a good idea to create a public branch so that any people working on it don't step on each other's toes/waste time by fixing the same issues.

**Comment by jabdoa2** [comment]
Hi colin, 

We are totally up to that. Feel free to create PRs. Unfortunately, some of the messages are false positives. E.g. most (probably all) unused imports are caused by type annotations. Feel free to fix all the others. 


Jan

**Comment by jabdoa2** [comment]
I looked into this a bit. You can install prospector (via pip3) locally and run it from within the MPF directory to get the same messages locally without pushing the code all the time. This also shows less false positives for me. You can also do PRs per file (or directory) if you want. We will merge that.
