### ISSUE TITLE
Provide shutdown reason

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#995]
I wonder if we should add the ability to the various shutdown & stop methods to include a reason for the shutdown/stop?

The example is from the forum.. an MC crash that caused it to disconnect, which in turn caused MPF to shut down. The MPF logs didn't show anything since MPF shut down gracefully, so it was confusing as to what was happening.

So maybe we can add a param to the shutdown event which is a string of a reason for shutdown, so in this case the MPF log could show that MPF shut down because the remote BCP client disconnected.

**Comment by jabdoa2** [comment]
Yeah I like it. This would require us to use different exceptions (similar to #922). Definitely worth it.

**Comment by toomanybrians** [comment]
Ah of course! Using our own exceptions would make this pretty much automatic.

**Comment by jabdoa2** [comment]
fixed in dev
